using LinqToDB;
using LinqToDB.Data;
using LinqToDB.Mapping;
using PolyPersist.Net.Common;

namespace PolyPersist.Net.RelationalStore.Dapper
{
    /// <summary>
    /// Relational (SQL) store built on linq2db. A single implementation serves every SQL provider
    /// (SQLite, PostgreSQL, ...): the dialect lives in the linq2db data provider, selected by
    /// <paramref name="provider"/> at construction time. The read side is LINQ (linq2db); raw SQL is
    /// reachable via <see cref="ITable{TRecord}"/>.GetUnderlyingImplementation() (e.g. Dapper), and
    /// joins across tables via <c>Query()</c> (the linq2db DataConnection).
    /// </summary>
    public class Relational_Store : IRelationalStore, ITransactionParticipant
    {
        private readonly string _provider;
        private readonly string _connectionString;

        // linq2db uses the property names as column names (consistently quoted per dialect); the
        // schema stays default. Records carry no linq2db attributes.
        internal readonly MappingSchema MappingSchema = new();

        /// <param name="provider">linq2db provider name, e.g. "SQLite.MS" or "PostgreSQL".</param>
        /// <param name="connectionString">the ADO.NET connection string for that provider.</param>
        public Relational_Store(string provider, string connectionString)
        {
            _provider = provider;
            _connectionString = connectionString;
        }

        /// <inheritdoc/>
        IStore.StorageModels IStore.StorageModel => IStore.StorageModels.Relational;
        /// <inheritdoc/>
        string IStore.ProviderName => $"Relational({_provider})";

        internal DataOptions Options()
            => new DataOptions().UseConnectionString(_provider, _connectionString).UseMappingSchema(MappingSchema);

        // Short-lived connection for a single operation. linq2db connections are cheap; the
        // underlying ADO connection is pooled.
        internal DataConnection CreateConnection() => new(Options());

        // Connection bound to a caller-supplied mapping schema (used by CreateTable, which must carry
        // the table name + primary key in the mapping instead of a runtime name override).
        internal DataConnection CreateConnection(MappingSchema schema)
            => new(new DataOptions().UseConnectionString(_provider, _connectionString).UseMappingSchema(schema));

        private bool _IsTableExists(string tableName)
        {
            // Probe the table directly: a SELECT against a missing table throws. This is reliable
            // across providers (the schema-provider metadata can lag a just-created table).
            using var db = CreateConnection();
            try
            {
                db.Execute($"SELECT 1 FROM \"{tableName}\" WHERE 1 = 0");
                return true;
            }
            catch
            {
                return false;
            }
        }

        // Bridges the class-constraint gap: linq2db requires `class`, but the interface only
        // guarantees `IRecord, new()`. At runtime TRecord is always a class, so the (class-
        // constrained) Relational_Table is built via reflection.
        // `bound` is null for a free-standing table (opens its own connection per operation) and the
        // scope's connection for a table taking part in a native transaction.
        internal ITable<TRecord> NewTable<TRecord>(string tableName, DataConnection? bound) where TRecord : IRecord, new()
        {
            var type = typeof(Relational_Table<>).MakeGenericType(typeof(TRecord));
            return (ITable<TRecord>)Activator.CreateInstance(type, tableName, this, bound)!;
        }

        /// <inheritdoc/>
        Task<bool> IRelationalStore.IsTableExists(string tableName)
            => Task.FromResult(_IsTableExists(tableName));

        /// <inheritdoc/>
        Task<ITable<TRecord>> IRelationalStore.GetTableByName<TRecord>(string tableName)
        {
            if (_IsTableExists(tableName) == false)
                throw new NotFoundException($"Table '{tableName}' does not exist in the relational store");

            return Task.FromResult(NewTable<TRecord>(tableName, bound: null));
        }

        /// <inheritdoc/>
        async Task<ITable<TRecord>> IRelationalStore.CreateTable<TRecord>(string tableName)
        {
            if (_IsTableExists(tableName) == true)
                throw new DuplicateKeyException($"Table '{tableName}' already exists in the relational store");

            var table = NewTable<TRecord>(tableName, bound: null);
            // DDL is generated by linq2db from the mapped record type (dialect-correct CREATE TABLE:
            // columns + primary key). NOTE (PP-36 dialect hook): a secondary index on PartitionKey is
            // a later optimization; Find/Delete filter by (PartitionKey, id) and work without it.
            await ((IRelationalTableInternal)table).CreateSchemaAsync().ConfigureAwait(false);
            return table;
        }

        /// <inheritdoc/>
        async Task IRelationalStore.DropTable(string tableName)
        {
            if (_IsTableExists(tableName) == false)
                throw new NotFoundException($"Table '{tableName}' does not exist in the relational store");

            using var db = CreateConnection();
            await db.ExecuteAsync($"DROP TABLE \"{tableName}\"").ConfigureAwait(false);
        }

        /// <inheritdoc/>
        async Task<ITransactionScope> ITransactionParticipant.BeginScope()
        {
            // One connection, one native transaction - so every table bound to this scope commits
            // together. The connection is opened here, at the start of Commit(), and released when
            // the scope is disposed; nothing pins it while the unit of work is being assembled.
            var db = CreateConnection();
            try
            {
                var tx = await db.BeginTransactionAsync().ConfigureAwait(false);
                return new Relational_TransactionScope(this, db, tx);
            }
            catch
            {
                db.Dispose();
                throw;
            }
        }
    }

    /// <summary>
    /// A native database transaction over one connection. Tables bound to it write through the open
    /// transaction, so a single Commit covers every table that took part.
    /// </summary>
    internal sealed class Relational_TransactionScope : ITransactionScope
    {
        private readonly Relational_Store _store;
        private readonly DataConnection _db;
        private readonly DataConnectionTransaction _tx;
        private bool _finished;

        internal Relational_TransactionScope(Relational_Store store, DataConnection db, DataConnectionTransaction tx)
        {
            _store = store;
            _db = db;
            _tx = tx;
        }

        /// <inheritdoc/>
        public ITable<TRecord> Bind<TRecord>(ITable<TRecord> table)
            where TRecord : IRecord, new()
            => _store.NewTable<TRecord>(table.Name, _db);

        /// <inheritdoc/>
        public async Task Commit()
        {
            await _tx.CommitAsync().ConfigureAwait(false);
            _finished = true;
        }

        /// <inheritdoc/>
        public async Task Rollback()
        {
            if (_finished == true)
                return;

            await _tx.RollbackAsync().ConfigureAwait(false);
            _finished = true;
        }

        public async ValueTask DisposeAsync()
        {
            // A scope that was never committed rolls back: the writes it holds must not leak out.
            if (_finished == false)
            {
                try { await _tx.RollbackAsync().ConfigureAwait(false); }
                catch { /* the connection may already be gone; disposing is all that is left */ }
            }

            await _tx.DisposeAsync().ConfigureAwait(false);
            await _db.DisposeAsync().ConfigureAwait(false);
        }
    }

    // Internal bridge so the (non-class-constrained) store can trigger DDL on a table whose
    // implementation is class-constrained.
    internal interface IRelationalTableInternal
    {
        Task CreateSchemaAsync();
    }
}
