using LinqToDB;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace PolyPersist.Net.AnalyticalStore.Postgres
{
    /// <summary>
    /// Analytical (OLAP) store on PostgreSQL, built on linq2db. Writing is batch-first
    /// (<see cref="IAnalyticalTable{TRecord}"/>.InsertBatch via linq2db BulkCopy = PostgreSQL COPY);
    /// the read side is LINQ (linq2db), so aggregations run in the database. PostgreSQL serves the
    /// analytical role at moderate scale. Raw SQL is reachable via GetUnderlyingImplementation().
    /// </summary>
    public class Postgres_AnalyticalStore : IAnalyticalStore
    {
        private const string _provider = "PostgreSQL";
        private readonly string _connectionString;

        // linq2db uses the property names as column names (quoted per dialect); no attributes needed.
        internal readonly MappingSchema MappingSchema = new();

        /// <param name="connectionString">the Npgsql connection string.</param>
        public Postgres_AnalyticalStore(string connectionString)
        {
            _connectionString = connectionString;
        }

        /// <inheritdoc/>
        IStore.StorageModels IStore.StorageModel => IStore.StorageModels.Analytical;
        /// <inheritdoc/>
        string IStore.ProviderName => "Analytical(PostgreSQL)";

        internal DataOptions Options()
            => new DataOptions().UseConnectionString(_provider, _connectionString).UseMappingSchema(MappingSchema);

        // Short-lived connection for a single operation; the underlying ADO connection is pooled.
        internal DataConnection CreateConnection() => new(Options());

        private bool _IsTableExists(string tableName)
        {
            // Probe the table directly: a SELECT against a missing table throws. Reliable across
            // providers (schema metadata can lag a just-created table).
            using var db = CreateConnection();
            try
            {
                db.Execute($"SELECT 1 FROM \"{tableName}\" WHERE 1 = 0");
                return true;
            }
            catch
            {
                return false;
            }
        }

        // Bridges the class-constraint gap: linq2db requires `class`, the interface only guarantees
        // `IAnalyticalRecord, new()`. At runtime TRecord is always a class, so the (class-constrained)
        // table is built via reflection.
        private IAnalyticalTable<TRecord> _NewTable<TRecord>(string tableName) where TRecord : IAnalyticalRecord, new()
        {
            var type = typeof(Postgres_AnalyticalTable<>).MakeGenericType(typeof(TRecord));
            return (IAnalyticalTable<TRecord>)Activator.CreateInstance(type, tableName, this)!;
        }

        /// <inheritdoc/>
        Task<bool> IAnalyticalStore.IsTableExists(string tableName)
            => Task.FromResult(_IsTableExists(tableName));

        /// <inheritdoc/>
        Task<IAnalyticalTable<TRecord>> IAnalyticalStore.GetTableByName<TRecord>(string tableName)
        {
            if (_IsTableExists(tableName) == false)
                throw new Exception($"Table '{tableName}' does not exist in the analytical store");

            return Task.FromResult(_NewTable<TRecord>(tableName));
        }

        /// <inheritdoc/>
        async Task<IAnalyticalTable<TRecord>> IAnalyticalStore.CreateTable<TRecord>(string tableName)
        {
            if (_IsTableExists(tableName) == true)
                throw new Exception($"Table '{tableName}' already exists in the analytical store");

            var table = _NewTable<TRecord>(tableName);
            // DDL is generated by linq2db from the mapped record type (dialect-correct CREATE TABLE).
            // Fact tables have no primary key / identity - they are append-only.
            await ((IAnalyticalTableInternal)table).CreateSchemaAsync().ConfigureAwait(false);
            return table;
        }

        /// <inheritdoc/>
        async Task IAnalyticalStore.DropTable(string tableName)
        {
            if (_IsTableExists(tableName) == false)
                throw new Exception($"Table '{tableName}' does not exist in the analytical store");

            using var db = CreateConnection();
            await db.ExecuteAsync($"DROP TABLE \"{tableName}\"").ConfigureAwait(false);
        }
    }

    // Internal bridge so the (non-class-constrained) store can trigger DDL on a table whose
    // implementation is class-constrained.
    internal interface IAnalyticalTableInternal
    {
        Task CreateSchemaAsync();
    }
}
