// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// IAnalyticalStore is a columnar OLAP / analytical store: batch (bulk) append on the write side,
	/// aggregation-oriented queries on the read side. It is a storage MODEL; reporting and BI are USES
	/// of it. Data typically lands here in PROCESSED form, projected from events or audit events by the
	/// consuming application - that projection pipeline is NOT part of PolyPersist; this store only
	/// provides the surface. Backends must speak SQL so the read side can use the same query engine as
	/// the relational store: ClickHouse (native OLAP), PostgreSQL (at moderate scale), or an in-memory
	/// store for testing. Cassandra is NOT a valid backend here (no SQL, not built for ad-hoc aggregation).
	public interface IAnalyticalStore : IStore
	{
		/// Checks whether a fact table exists in the store.
		public Task<bool> IsTableExists( string tableName );
		/// Retrieves a fact table by name. The row schema is derived from TRecord's mapping.
		public Task<IAnalyticalTable<TRecord>> GetTableByName<TRecord>( string tableName ) where TRecord: IAnalyticalRecord, new();
		/// Creates a new fact table. The schema is generated from TRecord by the implementation.
		public Task<IAnalyticalTable<TRecord>> CreateTable<TRecord>( string tableName ) where TRecord: IAnalyticalRecord, new();
		/// Drops an existing fact table.
		public Task DropTable( string tableName );
		/// ANALYTICAL query root spanning multiple tables (star-schema joins, cross-fact aggregation).
		/// Deliberately NOT portable to non-relational stores; the return value is generic - in .NET
		/// the linq2db DataConnection over which LINQ (and raw SQL) queries are written.
		public object Query();
	}
}
