// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// IAnalyticalRecord is the marker for a denormalized "fact" row in an analytical (OLAP) store.
	/// It is deliberately NOT an IEntity: analytical rows have no per-row identity, etag or
	/// concurrency control - they are append-only facts whose columns (dimensions and measures) are
	/// defined entirely by the concrete record's mapping.
	public interface IAnalyticalRecord
	{
	}
}
