// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// ICacheStore is a thin key-value cache with time-to-live. It is NOT a source of truth: values
	/// are transient and may be evicted or expire at any time. It is a storage MODEL (key-value + TTL);
	/// the caching STRATEGY (cache-aside, write-through, invalidation, repository decoration) is a
	/// cross-cutting service concern that belongs to SrvKit, which builds on top of this surface.
	///
	/// Values are arbitrary (a DTO, a string, a list, ...): the generic type is intentionally
	/// unconstrained, and the implementation serializes/deserializes it. Backends are key-value
	/// caches: Redis / Valkey (distributed, default), Memcached, an in-process memory cache (L1 /
	/// testing) or a managed equivalent.
	public interface ICacheStore : IStore
	{
		/// Stores a value under a key with a time-to-live.
		///
		/// @param key - the cache key.
		/// @param value - the value to cache; serialized by the implementation.
		/// @param ttlSeconds - the time-to-live in seconds; a value <= 0 means no expiration.
		public Task Set<T>( string key, T value, int ttlSeconds );
		/// Reads a value by key.
		///
		/// @param key - the cache key.
		/// @returns the cached value, or the type default (null for reference types) if the key is
		///          absent or has expired.
		public Task<T> Get<T>( string key );
		/// Checks whether a (non-expired) value exists for a key.
		public Task<bool> Exists( string key );
		/// Removes a value from the cache by key (a no-op if it is not present).
		public Task Remove( string key );
		/// Getting the underlying implementation.
		/// Please use this method carefully, because the returned value is different in every
		/// implementation. This is where PROVIDER-SPECIFIC capabilities live that the thin cache
		/// surface does not expose (e.g. atomic counters, pub/sub, native data structures in Redis).
		public object GetUnderlyingImplementation();
	}
}
