 
// <auto-generated>
//     This code was generated by unicontract
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// The ICollection interface defines a read-only property for the name of a collection.
	public interface ICollection
	{
		/// Read-only property representing the name of the collection.
		public string Name { get; }
	}
}
