 
// <auto-generated>
//     This code was generated by unicontract
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// IEntityPartitioned interface inherits from IEntity and adds a partition key for partitioned data stores.
	/// The 'PartitionKey' is used to segment data into partitions, often for scaling or distributing data across different nodes.
	/// In distributed databases, partitioning helps optimize performance and ensures efficient querying by reducing the scope of data scans.
	interface IEntityPartitioned
	{
		/// The 'PartitionKey' property represents the key used to partition data in distributed data stores.
		/// This allows for more efficient storage and retrieval of entities, especially in large-scale, partitioned systems.
		public string PartitionKey { get; }
	}
}
