// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// IEvent represents a single immutable event appended to a stream.
	/// It is deliberately NOT an IEntity: events are versioned by their STREAM (not by a per-event
	/// etag) and are never updated or deleted individually. An event is an append-only fact.
	public interface IEvent
	{
		/// The unique identifier of this event, primarily used for idempotency and de-duplication.
		/// If left empty on append, the store assigns one.
		public string eventId { get; set;}
		/// The stream this event belongs to (typically an aggregate instance id, or an audit
		/// category id). Set by the store on append.
		public string streamId { get; set;}
		/// The zero-based position of the event within its stream. This is the stream's
		/// optimistic-concurrency token. Set by the store on append.
		public int version { get; set;}
		/// The logical event type name, used for routing and for deserializing 'data' back into a
		/// concrete event type (e.g. "OrderPlaced", "PasswordChanged").
		public string eventType { get; set;}
		/// The serialized event payload (JSON).
		public string data { get; set;}
		/// Optional serialized metadata that travels with the event but is not part of its payload,
		/// such as correlation id, causation id or the acting user (JSON).
		public string metadata { get; set;}
		/// The moment the event was recorded. Set by the store on append.
		public DateTime timestamp { get; set;}
	}
}
