 
// <auto-generated>
//     This code was generated by unicontract
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	public interface IFile : IEntity
	{
		/// The 'fileName' property represents the name of the file as it is stored in the data store.
		/// This property can be used for human-readable identification or naming conventions.
		///
		/// Example:
		/// For a report named 'Monthly_Sales_Report.pdf', the 'fileName' would store the value 'Monthly_Sales_Report.pdf'.
		/// Applications can use this property to display the file's name in the user interface.
		public string fileName { get; set;}
		/// The 'contentType' property represents the MIME type of the file.
		/// This property is crucial for understanding the type of content stored in the file and determining
		/// how it should be processed or displayed to the user.
		///
		/// Example MIME Types:
		/// - 'application/pdf' for PDF documents.
		/// - 'image/png' for PNG images.
		/// - 'text/plain' for plain text files.
		///
		/// Applications can use this property to perform actions such as setting the appropriate headers
		/// for file downloads or displaying a file preview in the correct format.
		public string contentType { get; set;}
		/// The 'content' property represents the actual content or data of the file.
		/// This property stores the file data in a stream format, allowing for efficient handling
		/// of potentially large files that may not fit into memory all at once.
		///
		/// Example:
		/// For a file, 'example.pdf', the 'content' would store the binary data of the PDF file,
		/// enabling it to be uploaded, downloaded, or processed as needed.
		///
		/// The 'stream' format allows for the file's content to be processed in chunks or sequentially,
		/// making it ideal for large files or network transfers.
		public Stream content { get; set;}
	}
}
