// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// IRecord represents a single row of a relational (SQL) table.
	/// It is the relational counterpart of IDocument (document store) and IRow (column store):
	/// a plain entity (id / etag / PartitionKey / LastUpdate) with no extra members.
	public interface IRecord : IEntity
	{
	}
}
