// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// IRelationalStore is the relational (SQL) logical store. It extends the generic IStore and
	/// adds table-level operations. A single implementation (backed by linq2db) covers every SQL
	/// provider (PostgreSQL, Oracle, SQL Server, SQLite): the dialect lives in the provider layer,
	/// not in this contract or in the caller.
	public interface IRelationalStore : IStore
	{
		/// Asynchronous method to check whether a table exists in the store.
		///
		/// @param tableName - The name of the table to check for existence.
		/// @returns A boolean value indicating if the table is present in the store.
		public Task<bool> IsTableExists( string tableName );
		/// Asynchronous method to retrieve a table by its name.
		/// The row schema is derived from TRecord's mapping.
		///
		/// @param tableName - The name of the table to retrieve.
		/// @returns An ITable representing the table with the specified name.
		public Task<ITable<TRecord>> GetTableByName<TRecord>( string tableName ) where TRecord: IRecord, new();
		/// Asynchronous method to create a new table.
		/// The schema (columns, primary key) is generated from TRecord by the implementation
		/// (linq2db CreateTable), so the DDL is dialect-correct without hand-written SQL.
		///
		/// @param tableName - The name of the new table to be created.
		/// @returns The newly created table, represented as an ITable.
		public Task<ITable<TRecord>> CreateTable<TRecord>( string tableName ) where TRecord: IRecord, new();
		/// Asynchronous method to drop (delete) an existing table from the store.
		///
		/// @param tableName - The name of the table to be dropped.
		public Task DropTable( string tableName );
		/// RELATIONAL-ONLY query root for joins / multi-table / set-based SELECTs.
		/// This is deliberately NOT portable to document/column stores, therefore it lives on the
		/// relational store only. The return value is generic (in .NET the linq2db DataConnection,
		/// over which LINQ joins are written; the same handle also serves raw SQL via Dapper).
		public object Query();
	}
}
