// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// ISearchDocument is the marker for a document held in a search index.
	/// It is deliberately NOT an IEntity: a search document is a denormalized, derived projection of
	/// primary data, so it carries no etag / partition / concurrency - only an 'id' used to address
	/// the document for indexing (upsert) and deletion.
	public interface ISearchDocument
	{
		/// The identifier of the document within the index, used to upsert and delete it.
		public string id { get; set;}
	}
}
