// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// ISearchStore is a full-text search / index store (e.g. OpenSearch). It is a storage MODEL;
	/// searching is a USE. It is a SECONDARY, query-only store: documents are indexed here as a
	/// derived projection of primary data (that projection pipeline is app/consumer logic, NOT part
	/// of PolyPersist; this store only provides the surface).
	///
	/// The read side is NOT SQL/linq2db - search is expressed in the engine's own query model.
	/// Therefore only a thin, portable core is exposed here (index / delete / simple full-text search);
	/// advanced capabilities (relevance tuning, facets/aggregations, highlighting, suggestions) are
	/// reached through GetUnderlyingImplementation with the native client.
	///
	/// Backends: OpenSearch (native), an in-memory store for testing, and PostgreSQL full-text search
	/// for moderate needs.
	public interface ISearchStore : IStore
	{
		/// Checks whether an index exists in the store.
		public Task<bool> IsIndexExists( string indexName );
		/// Retrieves an index by name. The document schema is derived from TDocument's mapping.
		public Task<ISearchIndex<TDocument>> GetIndexByName<TDocument>( string indexName ) where TDocument: ISearchDocument, new();
		/// Creates a new index. The mapping is derived from TDocument by the implementation.
		public Task<ISearchIndex<TDocument>> CreateIndex<TDocument>( string indexName ) where TDocument: ISearchDocument, new();
		/// Drops an existing index.
		public Task DropIndex( string indexName );
	}
}
