// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// ISearchIndex represents a single search index. Documents are indexed (upserted) by id and
	/// deleted by id. The Search method covers the common full-text case; anything more advanced goes
	/// through GetUnderlyingImplementation.
	public interface ISearchIndex<TDocument>
		where TDocument: ISearchDocument, new()
	{
		/// Read-only property for parent Store.
		public IStore ParentStore { get; }
		/// Read-only property representing the name of the index.
		public string Name { get; }

		/// Indexes (upserts) a single document by its id.
		public Task Index( TDocument document );
		/// Indexes (upserts) a batch of documents in one round-trip.
		public Task IndexBatch( IList<TDocument> documents );
		/// Removes a document from the index by its id.
		public Task Delete( string id );
		/// Full-text search over the index, with paging.
		///
		/// @param queryText - the free-text query.
		/// @param mode - FullText (exact, whole-word, fast) or Fuzzy (substring + typo tolerant, slower).
		/// @param from - the zero-based offset of the first hit to return.
		/// @param size - the maximum number of hits to return.
		/// @returns the matching documents, most relevant first.
		public Task<IList<TDocument>> Search( string queryText, SearchMode mode, int from, int size );
		/// Getting the underlying implementation.
		/// Please use this method carefully, because the returned value is different in every
		/// implementation. This is where PROVIDER-SPECIFIC search capabilities live (relevance
		/// tuning, facets / aggregations, highlighting, suggesters), which are not portable.
		public object GetUnderlyingImplementation();
	}
}
