// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// ITable defines CRUD and single-table query operations on a relational table.
	/// This surface IS portable: it mirrors IDocumentCollection / IColumnTable, so cross-store code
	/// keeps working. Query() returns the language-native queryable (LINQ in .NET); joins are written
	/// in the host language over these queryables (advanced multi-table access via GetUnderlyingImplementation).
	public interface ITable<TRecord>
		where TRecord: IRecord, new()
	{
		/// Read-only property for parent Store.
		public IStore ParentStore { get; }
		/// Read-only property representing the name of the table.
		public string Name { get; }

		/// Asynchronous method to insert a row into the table.
		/// The 'record' parameter is the row that will be inserted into the table.
		public Task Insert( TRecord record );
		/// Asynchronous method to update an existing row in the table.
		/// Optimistic concurrency is enforced via the entity's etag.
		public Task Update( TRecord record );
		/// Asynchronous method to delete a row using its PartitionKey and id.
		public Task Delete( string partitionKey, string id );
		/// Asynchronous method to find a row by its PartitionKey and id.
		/// Returns the row if found, or null if not found.
		public Task<TRecord> Find( string partitionKey, string id );
		/// Portable, single-table query SCOPED to one partition: the returned queryable is already
		/// filtered to rows whose PartitionKey == partitionKey. A caller cannot widen it back
		/// (a .Where is additive; a different partitionKey yields an empty result, not a leak), which
		/// keeps ad-hoc queries partition-safe by default - mirroring Find(partitionKey, id).
		/// Language-mapped: .NET IQueryable<TRecord>, Java Stream<TRecord>, ...
		public System.Linq.IQueryable<TRecord> Query( string partitionKey );
		/// Explicit CROSS-PARTITION query: an unfiltered queryable spanning every partition. Use it
		/// deliberately for admin / reporting / migration scans; it is the opt-out from the
		/// partition-scoped default and can full-scan (multi-tenant leakage is the caller's concern).
		public System.Linq.IQueryable<TRecord> QueryCrossPartition();
		/// Getting the underlying implementation.
		/// Please use this method carefully, because the returned value is different in every
		/// implementation (e.g. the linq2db DataConnection, or the raw DbConnection for Dapper).
		public object GetUnderlyingImplementation();
	}
}
