// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// ITable defines CRUD and single-table query operations on a relational table.
	/// This surface IS portable: it mirrors IDocumentCollection / IColumnTable, so cross-store code
	/// keeps working. Joins are NOT here (they are not portable) - use IRelationalStore.Query().
	public interface ITable<TRecord>
		where TRecord: IRecord, new()
	{
		/// Read-only property for parent Store.
		public IStore ParentStore { get; }
		/// Read-only property representing the name of the table.
		public string Name { get; }

		/// Asynchronous method to insert a row into the table.
		/// The 'record' parameter is the row that will be inserted into the table.
		public Task Insert( TRecord record );
		/// Asynchronous method to update an existing row in the table.
		/// Optimistic concurrency is enforced via the entity's etag.
		public Task Update( TRecord record );
		/// Asynchronous method to delete a row using its PartitionKey and id.
		public Task Delete( string partitionKey, string id );
		/// Asynchronous method to find a row by its PartitionKey and id.
		/// Returns the row if found, or null if not found.
		public Task<TRecord> Find( string partitionKey, string id );
		/// Portable, SINGLE-TABLE query interface (filter / project / order).
		/// The return value is generic, so the implementation can define the real type:
		/// in .NET an IQueryable<T>, in Java a Stream / Querydsl, etc.
		public object Query<T>() where T: TRecord, new();
		/// Getting the underlying implementation.
		/// Please use this method carefully, because the returned value is different in every
		/// implementation (e.g. the linq2db DataConnection, or the raw DbConnection for Dapper).
		public object GetUnderlyingImplementation();
	}
}
