// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
#nullable enable

using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// IValidationError is an interface that represents a validation error occurring during the validation process.
	/// It provides structured details about the nature and location of the error within the entity.
	public interface IValidationError
	{
		/// Represents the type or class name of the entity where the validation error occurred.
		/// For example, it might be "User", "Order", or "Product".
		public string TypeOfEntity { get; }
		/// Indicates the specific member or property of the entity that caused the validation error.
		/// For example, it could be "Username", "OrderDate", or "Price".
		public string MemberOfEntity { get; }
		/// Where the error is, relative to the object Validate was called on:
		/// "quantity", "items[1].quantity", "billingAddress.country". This is what lets a caller
		/// address the failure - mark the right control on a form - instead of only reading a
		/// sentence. For a rule on the object's own member it is simply the member name.
		public string Path { get; }
		/// A human-readable description of the error, explaining what went wrong.
		/// This is useful for displaying error messages to users or logging them for debugging.
		public string ErrorText { get; }
	}
}
