 
// <auto-generated>
//     This code was generated by unicontract
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{
	/// IValidabale is an interface that defines a validation mechanism for entities.
	/// Classes or structs implementing this interface must provide logic to validate themselves 
	/// and collect validation errors if any are found.
	///
	/// The validation process ensures that the entity adheres to certain rules or constraints 
	/// defined in the implementing class.
	public interface IValidable
	{
		/// Validates the current entity and populates the errors list with any validation errors encountered.
		///
		/// @param errors: A list of IValidationError objects that will be populated with errors if the validation fails.
		/// @returns: A boolean indicating whether the validation succeeded (true) or failed (false).
		public bool Validate( IList<IValidationError> errors );
	}
}
