// <auto-generated>
//     This code was generated by the UniContract interpreter
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PolyPersist
{

	/// SearchMode selects how the query text is matched against the indexed documents.
	public enum SearchMode
	{
		/// Exact, whole-word full-text matching (the query terms must appear as whole tokens). Fast.
		FullText,
		/// Loose matching, for when exact is too strict. A document matches when it CONTAINS a query
		/// term as a fragment (substring, anywhere in a word) OR fuzzily matches it (typo tolerance,
		/// small edit distance). The two are unioned. Slower than FullText, and may need extra index-
		/// time structures (e.g. PostgreSQL trigram index); the exact fuzzy distance / fragment rules
		/// are engine-specific.
		Fuzzy,
	}

}
