/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// IAnalyticalStore is a columnar OLAP / analytical store: batch (bulk) append on the write side,
// aggregation-oriented queries on the read side. It is a storage MODEL; reporting and BI are USES
// of it. Data typically lands here in PROCESSED form, projected from events or audit events by the
// consuming application - that projection pipeline is NOT part of PolyPersist; this store only
// provides the surface. Backends must speak SQL so the read side can use the same query engine as
// the relational store: ClickHouse (native OLAP), PostgreSQL (at moderate scale), or an in-memory
// store for testing. Cassandra is NOT a valid backend here (no SQL, not built for ad-hoc aggregation).
public interface IAnalyticalStore extends IStore {
	// Checks whether a fact table exists in the store.
	CompletableFuture<Boolean> IsTableExists(String tableName);
	// Retrieves a fact table by name. The row schema is derived from TRecord's mapping.
	<TRecord extends IAnalyticalRecord> CompletableFuture<IAnalyticalTable<TRecord>> GetTableByName(String tableName);
	// Creates a new fact table. The schema is generated from TRecord by the implementation.
	<TRecord extends IAnalyticalRecord> CompletableFuture<IAnalyticalTable<TRecord>> CreateTable(String tableName);
	// Drops an existing fact table.
	CompletableFuture<Void> DropTable(String tableName);
}
