/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// IAnalyticalTable represents a single fact table. Writing is BATCH-first (bulk append); there is
// deliberately NO per-row Insert / Update / Delete / Find, because that would misrepresent an OLAP
// engine (single-row writes are an anti-pattern; row mutation is a heavy async operation).
public interface IAnalyticalTable<TRecord extends IAnalyticalRecord> {
	// Read-only property for parent Store.
	IStore getParentStore();
	// Read-only property representing the name of the table.
	String getName();

	// Bulk-appends a batch of fact rows. This is the only write path: OLAP engines are optimized
	// for batched ingestion, so callers should accumulate rows and append them together.
	CompletableFuture<Void> InsertBatch(List<TRecord> records);
	// Single-table analytical query (aggregation / GROUP BY / scan) SCOPED to one partition: the
	// returned queryable is already filtered to rows whose PartitionKey == partitionKey. Use it
	// for tenant-scoped analytics; a caller cannot widen it back across partitions.
	// Language-mapped: .NET IQueryable<TRecord>, Java Stream<TRecord>, ...
	Stream<TRecord> Query(String partitionKey);
	// Explicit CROSS-PARTITION analytical query: an unfiltered queryable spanning every partition.
	// This is the natural BI / reporting path for an OLAP store (aggregate across all tenants);
	// it is the deliberate opt-out from the partition-scoped Query.
	Stream<TRecord> QueryCrossPartition();
	// Getting the underlying implementation.
	// Please use this method carefully, because the returned value is different in every
	// implementation (e.g. the linq2db DataConnection, or the raw DbConnection).
	Object GetUnderlyingImplementation();
}
