/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// The IBlobStore interface defines operations for managing blob storage containers.
// Containers serve as logical units for organizing and isolating blobs.
//
// Examples:
// - A container named 'UserUploads' storing all user-uploaded files.
// - A container named 'Logs' for storing application logs.
public interface IBlobStore extends IStore {
	// Checks whether a container exists in the blob storage.
	//
	// Parameters:
	// - containerName: The name of the container to check.
	//
	// Returns:
	// - Boolean value indicating whether the container exists.
	//
	// Use Case:
	// Before attempting to access or create a container, check if it already exists.
	CompletableFuture<Boolean> IsContainerExists(String containerName);
	// Retrieves a container by its name.
	//
	// Parameters:
	// - containerName: The name of the container to retrieve.
	//
	// Returns:
	// - An instance of IBlobContainer representing the requested container.
	//
	// Generic Constraint:
	// - TBlob must implement the IBlob interface, ensuring type safety for blob operations.
	//
	// Use Case:
	// Retrieve a container to perform blob operations like uploading or downloading files.
	<TBlob extends IBlob> CompletableFuture<IBlobContainer<TBlob>> GetContainerByName(String containerName);
	// Creates a new container in the blob storage.
	//
	// Parameters:
	// - containerName: The name of the container to create.
	//
	// Returns:
	// - An instance of IBlobContainer representing the newly created container.
	//
	// Generic Constraint:
	// - TBlob must implement the IBlob interface, ensuring type safety for blob operations.
	//
	// Use Case:
	// Create a container for a specific group of files, such as user uploads or application logs.
	<TBlob extends IBlob> CompletableFuture<IBlobContainer<TBlob>> CreateContainer(String containerName);
	// Deletes an existing container from the blob storage.
	//
	// Parameters:
	// - containerName: The name of the container to delete.
	//
	// Use Case:
	// Remove containers that are no longer needed, freeing up storage space and reducing costs.
	CompletableFuture<Void> DropContainer(String containerName);
}
