/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// The IBlobContainer interface defines operations for managing blobs within a specific container.
// It provides functionality for uploading, downloading, deleting, and updating blobs, as well as retrieving metadata.
//
// Examples:
// - A container for user-uploaded photos, where each blob represents an image.
// - A container for logs, where each blob is a log file.
public interface IBlobContainer<TBlob extends IBlob> {
	// Read-only property for parent Store.
	IStore getParentStore();
	// Read-only property representing the name of the container.
	//
	// Example:
	// If the container is named 'UserFiles', this property holds the value 'UserFiles'.
	String getName();

	// Uploads a blob and its content to the container.
	//
	// Parameters:
	// - blob: The blob entity to upload.
	// - content: The stream containing the blob's content.
	//
	// Use Case:
	// Add a new file to the container with its associated metadata.
	CompletableFuture<Void> Upload(TBlob blob, InputStream content);
	// Downloads the content of a blob from the container.
	//
	// Parameters:
	// - blob: The blob entity to download.
	//
	// Returns:
	// - A stream containing the blob's content.
	//
	// Use Case:
	// Retrieve a file for viewing or processing.
	CompletableFuture<InputStream> Download(TBlob blob);
	// Deletes a blob from the container.
	//
	// Parameters:
	// - partitionKey: The partition key of the blob.
	// - id: The unique identifier of the blob.
	//
	// Use Case:
	// Remove a file that is no longer needed from the container.
	CompletableFuture<Void> Delete(String partitionKey, String id);
	// Finds a blob in the container by its partition key and ID.
	//
	// Parameters:
	// - partitionKey: The partition key of the blob.
	// - id: The unique identifier of the blob.
	//
	// Returns:
	// - A stream containing the blob's content.
	//
	// Use Case:
	// Locate and retrieve a specific file from the container.
	CompletableFuture<TBlob> Find(String partitionKey, String id);
	// Updates the content of an existing blob in the container.
	//
	// Parameters:
	// - blob: The blob entity to update.
	// - content: The stream containing the new content.
	//
	// Use Case:
	// Modify the content of an existing file, such as updating a document.
	CompletableFuture<Void> UpdateContent(TBlob blob, InputStream content);
	// Updates the metadata of an existing blob in the container.
	//
	// Parameters:
	// - blob: The blob entity whose metadata is to be updated.
	//
	// Use Case:
	// Modify metadata, such as changing the description or tags associated with a file.
	CompletableFuture<Void> UpdateMetadata(TBlob blob);
	// Retrieves the underlying implementation of the blob container.
	//
	// Returns:
	// - A value of type `any` that provides direct access to the underlying storage implementation.
	//
	// Use Case:
	// Use this method for advanced operations that are not covered by the standard interface.
	// Note: This method should be used cautiously, as the returned object is implementation-specific.
	Object GetUnderlyingImplementation();
}
