/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// ICacheEntry is the outcome of a TryGet lookup: whether the key was there, and what it held.
//
// Get returns the type default when a key is absent, which is unambiguous only for reference
// types. For a VALUE type it is not: a cached 0, false or DateTime.MinValue is indistinguishable
// from a miss, so the caller either recomputes a perfectly good cached value or has to call
// Exists first - two round trips, with a race in between. This carrier answers both questions in
// one call. It is deliberately a return value rather than an out-parameter, because out-parameters
// do not exist in every target language.
public interface ICacheEntry<T> {
	// True if the key was present and had not expired; false for a miss.
	boolean getFound();
	// The cached value when Found is true; the type default otherwise.
	T getValue();
}
