/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// ICacheStore is a thin key-value cache with time-to-live. It is NOT a source of truth: values
// are transient and may be evicted or expire at any time. It is a storage MODEL (key-value + TTL);
// the caching STRATEGY (cache-aside, write-through, invalidation, repository decoration) is a
// cross-cutting service concern that belongs to SrvKit, which builds on top of this surface.
//
// Values are arbitrary (a DTO, a string, a list, ...): the generic type is intentionally
// unconstrained, and the implementation serializes/deserializes it. Backends are key-value
// caches: Redis / Valkey (distributed, default), Memcached, an in-process memory cache (L1 /
// testing) or a managed equivalent.
public interface ICacheStore extends IStore {
	// Stores a value under a key with a time-to-live.
	//
	// @param key - the cache key.
	// @param value - the value to cache; serialized by the implementation.
	// @param ttlSeconds - the time-to-live in seconds; a value <= 0 means no expiration.
	<T> CompletableFuture<Void> Set(String key, T value, int ttlSeconds);
	// Reads a value by key.
	//
	// @param key - the cache key.
	// @returns the cached value, or the type default (null for reference types) if the key is
	//          absent or has expired.
	<T> CompletableFuture<T> Get(String key);
	// Reads a value by key, reporting whether it was there at all.
	//
	// Prefer this over Get whenever T can be a value type, or whenever "absent" and "cached
	// default" have to be told apart. It answers in a single round trip what Exists + Get would
	// answer in two (and without the race between them).
	//
	// @param key - the cache key.
	// @returns an entry whose Found is true and Value is the cached value, or whose Found is
	//          false when the key is absent or has expired.
	<T> CompletableFuture<ICacheEntry<T>> TryGet(String key);
	// Checks whether a (non-expired) value exists for a key.
	CompletableFuture<Boolean> Exists(String key);
	// Removes a value from the cache by key (a no-op if it is not present).
	CompletableFuture<Void> Remove(String key);
	// Getting the underlying implementation.
	// Please use this method carefully, because the returned value is different in every
	// implementation. This is where PROVIDER-SPECIFIC capabilities live that the thin cache
	// surface does not expose (e.g. atomic counters, pub/sub, native data structures in Redis).
	Object GetUnderlyingImplementation();
}
