/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

public interface IColumnTable<TRow extends IRow> {
	// Read-only property for parent Store.
	IStore getParentStore();
	// Read-only property representing the name of the table.
	String getName();

	// Asynchronous method to insert an row into the columntable.
	// The 'row' parameter is the row that will be inserted into the table.
	CompletableFuture<Void> Insert(TRow row);
	// Asynchronous method to update an existing row in the columntable.
	// The 'row' parameter represents the row to be updated in the columntable.
	CompletableFuture<Void> Update(TRow row);
	// Asynchronous method to delete an row using its ID and PartitionKey.
	// The 'id' parameter is the unique identifier of the row, and 'partitionKey' is used for partitioning the data in distributed data stores.
	CompletableFuture<Void> Delete(String partitionKey, String id);
	// Asynchronous method to find an row by its ID and PartitionKey.
	// The 'id' parameter is the unique identifier of the row, and 'partitionKey' is used to partition data.
	// Returns the row if found, or null if not found.
	CompletableFuture<Optional<TRow>> Find(String partitionKey, String id);
	// Query interface SCOPED to one partition: the returned queryable is already filtered to
	// rows whose PartitionKey == partitionKey. A caller cannot widen it back (a .Where is
	// additive; a different partitionKey yields an empty result, not a leak), which keeps ad-hoc
	// queries partition-safe by default - mirroring Find(partitionKey, id). On Cassandra this is
	// a single-partition query (no ALLOW FILTERING).
	// Language-mapped: .NET IQueryable<TRow>, Java Stream<TRow>, Python Iterable[TRow].
	Stream<TRow> Query(String partitionKey);
	// Explicit CROSS-PARTITION query: an unfiltered queryable spanning every partition. Use it
	// deliberately for admin / reporting / migration scans; it is the opt-out from the
	// partition-scoped default and can full-scan (multi-tenant leakage is the caller's concern).
	Stream<TRow> QueryCrossPartition();
	// getting the underlying implementation
	// please use this method carefully, because the returned value is different in every implementation
	Object GetUnderlyingImplementation();
}
