/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// The ICollection interface defines methods for CRUD operations on entities.
// This interface is used for collections that store entities.
public interface IDocumentCollection<TDocument extends IDocument> {
	// Read-only property for parent Store.
	IStore getParentStore();
	// Read-only property representing the name of the collection.
	String getName();

	// Asynchronous method to insert an document into the collection.
	// The 'document' parameter is the document that will be inserted into the collection.
	CompletableFuture<Void> Insert(TDocument document);
	// Asynchronous method to update an existing document in the collection.
	// The 'document' parameter represents the document to be updated in the collection.
	CompletableFuture<Void> Update(TDocument document);
	// Asynchronous method to delete an document using its ID and PartitionKey.
	// The 'id' parameter is the unique identifier of the document, and 'partitionKey' is used for partitioning the data in distributed data stores.
	CompletableFuture<Void> Delete(String partitionKey, String id);
	// Asynchronous method to find an document by its ID and PartitionKey.
	// The 'id' parameter is the unique identifier of the document, and 'partitionKey' is used to partition data.
	// Returns the document if found, or null if not found.
	CompletableFuture<Optional<TDocument>> Find(String partitionKey, String id);
	// Query interface SCOPED to one partition: the returned queryable is already filtered to
	// documents whose PartitionKey == partitionKey. A caller cannot widen it back (a .Where is
	// additive; a different partitionKey yields an empty result, not a leak), which keeps ad-hoc
	// queries partition-safe by default - mirroring Find(partitionKey, id).
	// Language-mapped: .NET IQueryable<TDocument>, Java Stream<TDocument>, Python Iterable[TDocument].
	Stream<TDocument> Query(String partitionKey);
	// Explicit CROSS-PARTITION query: an unfiltered queryable spanning every partition. Use it
	// deliberately for admin / reporting / migration scans; it is the opt-out from the
	// partition-scoped default and can full-scan (multi-tenant leakage is the caller's concern).
	Stream<TDocument> QueryCrossPartition();
	// getting the underlying implementation
	// please use this method carefully, because the returned value is different in every implementation
	Object GetUnderlyingImplementation();
}
