/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// IEvent represents a single immutable event appended to a stream.
// It is deliberately NOT an IEntity: events are versioned by their STREAM (not by a per-event
// etag) and are never updated or deleted individually. An event is an append-only fact.
public interface IEvent {
	// The unique identifier of this event, primarily used for idempotency and de-duplication.
	// If left empty on append, the store assigns one.
	String getEventId();
	void setEventId(String value);
	// The stream this event belongs to (typically an aggregate instance id, or an audit
	// category id). Set by the store on append.
	String getStreamId();
	void setStreamId(String value);
	// The zero-based position of the event within its stream. This is the stream's
	// optimistic-concurrency token. Set by the store on append.
	int getVersion();
	void setVersion(int value);
	// The logical event type name, used for routing and for deserializing 'data' back into a
	// concrete event type (e.g. "OrderPlaced", "PasswordChanged").
	String getEventType();
	void setEventType(String value);
	// The serialized event payload (JSON).
	String getData();
	void setData(String value);
	// Optional serialized metadata that travels with the event but is not part of its payload,
	// such as correlation id, causation id or the acting user (JSON).
	String getMetadata();
	void setMetadata(String value);
	// The moment the event was recorded. Set by the store on append.
	LocalDateTime getTimestamp();
	void setTimestamp(LocalDateTime value);
}
