/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// IEventStore is an append-only, immutable, ordered stream store. It is a storage MODEL;
// event sourcing and audit trails are USES of it - both domain events and audit events are
// just events on streams. A single implementation family can be backed by EventStoreDB, by
// Cassandra (partition = stream, clustering = version), or by an in-memory store for testing.
public interface IEventStore extends IStore {
	// Appends events to the end of a stream with optimistic concurrency.
	//
	// @param streamId - the target stream (aggregate/category id).
	// @param expectedVersion - the caller's last-known version of the stream. Sentinels:
	//        -2 = Any (no concurrency check); -1 = the stream must not yet exist (empty);
	//        >= 0 = the stream's current last version must equal this value, otherwise the
	//        append is rejected as a concurrency conflict.
	// @param events - the events to append, in order.
	// @returns the new last version of the stream after the append.
	CompletableFuture<Integer> AppendToStream(String streamId, int expectedVersion, List<IEvent> events);
	// Reads a slice of a stream forward, in ascending version order.
	//
	// @param streamId - the stream to read.
	// @param fromVersion - the zero-based version to start reading from.
	// @param maxCount - the maximum number of events to return; -1 means "read to the end".
	// @returns the events in ascending version order; empty if the stream does not exist.
	CompletableFuture<List<IEvent>> ReadStream(String streamId, int fromVersion, int maxCount);
	// Checks whether a stream exists (has at least one event).
	//
	// @param streamId - the stream to check.
	// @returns true if the stream exists.
	CompletableFuture<Boolean> StreamExists(String streamId);
	// Returns the current last version of a stream, or -1 if the stream does not exist.
	//
	// @param streamId - the stream to inspect.
	CompletableFuture<Integer> GetStreamVersion(String streamId);
	// Deletes (tombstones) an entire stream. Individual events are never deleted; this removes
	// the whole stream (e.g. for GDPR erasure). expectedVersion follows the AppendToStream
	// sentinels.
	//
	// @param streamId - the stream to delete.
	// @param expectedVersion - concurrency guard, see AppendToStream.
	CompletableFuture<Void> DeleteStream(String streamId, int expectedVersion);
	// Getting the underlying implementation.
	// Please use this method carefully, because the returned value is different in every
	// implementation. This is also where PROVIDER-SPECIFIC, non-portable capabilities live -
	// most notably subscriptions / projections / category ($all) reads, which are native in
	// EventStoreDB but emulated or limited on other backends.
	Object GetUnderlyingImplementation();
}
