/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// IRecord represents a single row of a relational (SQL) table.
// It is the relational counterpart of IDocument (document store) and IRow (column store):
// a plain entity (id / etag / PartitionKey / LastUpdate) with no extra members.
public interface IRecord extends IEntity {
}
