/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// IRelationalStore is the relational (SQL) logical store. It extends the generic IStore and
// adds table-level operations. A single implementation (backed by linq2db) covers every SQL
// provider (PostgreSQL, Oracle, SQL Server, SQLite): the dialect lives in the provider layer,
// not in this contract or in the caller.
public interface IRelationalStore extends IStore {
	// Asynchronous method to check whether a table exists in the store.
	//
	// @param tableName - The name of the table to check for existence.
	// @returns A boolean value indicating if the table is present in the store.
	CompletableFuture<Boolean> IsTableExists(String tableName);
	// Asynchronous method to retrieve a table by its name.
	// The row schema is derived from TRecord's mapping.
	//
	// @param tableName - The name of the table to retrieve.
	// @returns An ITable representing the table with the specified name.
	<TRecord extends IRecord> CompletableFuture<ITable<TRecord>> GetTableByName(String tableName);
	// Asynchronous method to create a new table.
	// The schema (columns, primary key) is generated from TRecord by the implementation
	// (linq2db CreateTable), so the DDL is dialect-correct without hand-written SQL.
	//
	// @param tableName - The name of the new table to be created.
	// @returns The newly created table, represented as an ITable.
	<TRecord extends IRecord> CompletableFuture<ITable<TRecord>> CreateTable(String tableName);
	// Asynchronous method to drop (delete) an existing table from the store.
	//
	// @param tableName - The name of the table to be dropped.
	CompletableFuture<Void> DropTable(String tableName);
}
