/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// ISearchDocument is the marker for a document held in a search index.
// It is deliberately NOT an IEntity: a search document is a denormalized, derived projection of
// primary data, so it carries no etag / partition / concurrency - only an 'id' used to address
// the document for indexing (upsert) and deletion.
public interface ISearchDocument {
	// The identifier of the document within the index, used to upsert and delete it.
	String getId();
	void setId(String value);
}
