/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// ISearchIndex represents a single search index. Documents are indexed (upserted) by id and
// deleted by id. The Search method covers the common full-text case; anything more advanced goes
// through GetUnderlyingImplementation.
public interface ISearchIndex<TDocument extends ISearchDocument> {
	// Read-only property for parent Store.
	IStore getParentStore();
	// Read-only property representing the name of the index.
	String getName();

	// Indexes (upserts) a single document by its id.
	CompletableFuture<Void> Index(TDocument document);
	// Indexes (upserts) a batch of documents in one round-trip.
	CompletableFuture<Void> IndexBatch(List<TDocument> documents);
	// Removes a document from the index by its id.
	CompletableFuture<Void> Delete(String id);
	// Full-text search over the index, with paging.
	//
	// @param queryText - the free-text query.
	// @param mode - FullText (exact, whole-word, fast) or Fuzzy (substring + typo tolerant, slower).
	// @param from - the zero-based offset of the first hit to return.
	// @param size - the maximum number of hits to return.
	// @returns the matching documents, most relevant first.
	CompletableFuture<List<TDocument>> Search(String queryText, SearchMode mode, int from, int size);
	// Getting the underlying implementation.
	// Please use this method carefully, because the returned value is different in every
	// implementation. This is where PROVIDER-SPECIFIC search capabilities live (relevance
	// tuning, facets / aggregations, highlighting, suggesters), which are not portable.
	Object GetUnderlyingImplementation();
}
