/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

public interface ITransaction {

	// Defines supported transactional operations.
	public enum Operations {
		Insert,
		Update,
		Delete,
	}

	// Adds an existing document to the transaction for change tracking.
	<TDocument extends IDocument> void AddOriginal(IDocumentCollection<TDocument> collection, TDocument document);
	// Adds an existing row to the transaction for change tracking.
	<TRow extends IRow> void AddOriginal(IColumnTable<TRow> table, TRow row);
	// Adds an existing relational row to the transaction for change tracking.
	<TRecord extends IRecord> void AddOriginal(ITable<TRecord> table, TRecord record);
	// Adds an existing blob to the transaction for change tracking, including its content snapshot.
	<TBlob extends IBlob> CompletableFuture<Void> AddOriginal(IBlobContainer<TBlob> container, TBlob blob);
	// Inserts a new document and registers a rollback action to delete it if needed.
	<TDocument extends IDocument> CompletableFuture<Void> Insert(IDocumentCollection<TDocument> collection, TDocument document);
	// Inserts a new row and registers a rollback action to delete it if needed.
	<TRow extends IRow> CompletableFuture<Void> Insert(IColumnTable<TRow> table, TRow row);
	// Inserts a new relational row and registers a rollback action to delete it if needed.
	<TRecord extends IRecord> CompletableFuture<Void> Insert(ITable<TRecord> table, TRecord record);
	// Uploads a new blob and registers a rollback action to delete it if needed.
	<TBlob extends IBlob> CompletableFuture<Void> Upload(IBlobContainer<TBlob> container, TBlob blob, InputStream content);
	// Updates an existing document and registers a rollback action to restore its original state if needed.
	<TDocument extends IDocument> CompletableFuture<Void> Update(IDocumentCollection<TDocument> collection, TDocument document);
	// Updates an existing row and registers a rollback action to restore its original state if needed.
	<TRow extends IRow> CompletableFuture<Void> Update(IColumnTable<TRow> table, TRow row);
	// Updates an existing relational row and registers a rollback action to restore its original state if needed.
	<TRecord extends IRecord> CompletableFuture<Void> Update(ITable<TRecord> table, TRecord record);
	// Updates the content of an existing blob and registers a rollback action to restore its original content if needed.
	<TBlob extends IBlob> CompletableFuture<Void> UpdateContent(IBlobContainer<TBlob> container, TBlob blob, InputStream content);
	// Updates the metadata of an existing blob and registers a rollback action to restore its original metadata if needed.
	<TBlob extends IBlob> CompletableFuture<Void> UpdateMetadata(IBlobContainer<TBlob> container, TBlob blob);
	// Deletes an existing document and registers a rollback action to re-insert its original state if needed.
	<TDocument extends IDocument> CompletableFuture<Void> Delete(IDocumentCollection<TDocument> collection, TDocument document);
	// Deletes an existing row and registers a rollback action to re-insert its original state if needed.
	<TRow extends IRow> CompletableFuture<Void> Delete(IColumnTable<TRow> table, TRow row);
	// Deletes an existing relational row and registers a rollback action to re-insert its original state if needed.
	<TRecord extends IRecord> CompletableFuture<Void> Delete(ITable<TRecord> table, TRecord record);
	// Deletes an existing blob and registers a rollback action to re-upload its original state if needed.
	<TBlob extends IBlob> CompletableFuture<Void> Delete(IBlobContainer<TBlob> container, TBlob blob);
	// Commits the transaction by executing all registered commit actions in parallel.
	CompletableFuture<Void> Commit();
	// Adds a custom rollback action to the transaction.
	CompletableFuture<Void> Rollback();
}
