/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;

// IValidabale is an interface that defines a validation mechanism for entities.
// Classes or structs implementing this interface must provide logic to validate themselves 
// and collect validation errors if any are found.
//
// The validation process ensures that the entity adheres to certain rules or constraints 
// defined in the implementing class.
public interface IValidable {
	// Validates the current entity and populates the errors list with any validation errors encountered.
	//
	// @param errors: A list of IValidationError objects that will be populated with errors if the validation fails.
	// @returns: A boolean indicating whether the validation succeeded (true) or failed (false).
	boolean Validate(List<IValidationError> errors);
}
