/*
 * <auto-generated>
 *     This code was generated by the UniContract interpreter
 *     see more information: https://github.com/gyorgy-gulyas/UniContract
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */
package PolyPersist;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.io.InputStream;
import java.util.stream.Stream;


// SearchMode selects how the query text is matched against the indexed documents.
public enum SearchMode {
	// Exact, whole-word full-text matching (the query terms must appear as whole tokens). Fast.
	FullText,
	// Loose matching, for when exact is too strict. A document matches when it CONTAINS a query
	// term as a fragment (substring, anywhere in a word) OR fuzzily matches it (typo tolerance,
	// small edit distance). The two are unioned. Slower than FullText, and may need extra index-
	// time structures (e.g. PostgreSQL trigram index); the exact fuzzy distance / fragment rules
	// are engine-specific.
	Fuzzy,
}

