# <auto-generated>
#     This code was generated by the UniContract interpreter
#     see more information: https://github.com/gyorgy-gulyas/UniContract
#
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>
from __future__ import annotations
from abc import ABC, abstractmethod
from enum import Enum
from typing import Any, List, Dict, Optional, Generic, TypeVar, BinaryIO, Iterable
from decimal import Decimal
from datetime import date, time, datetime


# SearchMode selects how the query text is matched against the indexed documents.
class SearchMode(Enum):
    # Exact, whole-word full-text matching (the query terms must appear as whole tokens). Fast.
    FullText = "FullText"
    # Loose matching, for when exact is too strict. A document matches when it CONTAINS a query
    # term as a fragment (substring, anywhere in a word) OR fuzzily matches it (typo tolerance,
    # small edit distance). The two are unioned. Slower than FullText, and may need extra index-
    # time structures (e.g. PostgreSQL trigram index); the exact fuzzy distance / fragment rules
    # are engine-specific.
    Fuzzy = "Fuzzy"


# IDataStore is the representation of a generic "data store" abstraction.
# This can be any type of database such as a SQL database, Document Database, ColumnStore (keyspace), Vector Database, etc.
# 
# The interface defines basic functionality that can be implemented on any type of database,
# regardless of whether it is a relational database, a NoSQL document store, a wide-column store, or a vector database.
#
# This abstraction ensures a uniform way to interact with various types of databases,
# while allowing flexibility for specific implementations tailored to the database type.
class IStore(ABC):


    # This enum defines various types of data stores or database representations.
    # Each entry represents a different data storage model suitable for specific data types and use cases.
    class StorageModels(Enum):
        # Relational databases (SQL) store data in structured tables and support complex queries through SQL.
        # Examples include MySQL, PostgreSQL, SQL Server, etc.
        Relational = "Relational"
        # Document-oriented databases store data in flexible formats like JSON or BSON.
        # They are ideal for semi-structured data and are used by systems like MongoDB, CouchDB, and CosmosDB.
        Document = "Document"
        # Vector databases are specialized for storing and searching large-scale, high-dimensional vector data.
        # These are used in machine learning, AI, and search systems, with examples like Faiss and Milvus.
        # Vector,
        # Graph databases store data as nodes and edges, representing entities and their relationships.
        # They are particularly useful for modeling complex networks, social graphs, and interconnected data.
        # Graph,
        # Key-value stores are simple and fast databases where data is stored as key-value pairs.
        # These are typically used for caching and simple lookups, such as Redis, DynamoDB, and Riak.
        # KeyValue,
        # Column store databases organize data into columns rather than rows, optimized for read-heavy workloads.
        # They are widely used in big data systems and include databases like Cassandra, ScyllaDB, and HBase.
        ColumnStore = "ColumnStore"
        # Event stores keep an append-only, ordered sequence of immutable events on
        # streams; they are the basis of event sourcing and also serve audit trails.
        # Examples include EventStoreDB (Kurrent); a stream store can also be backed by Cassandra.
        EventStore = "EventStore"
        # Analytical / OLAP stores are optimized for fast aggregation over large volumes of
        # append-only data (reporting, BI). Examples include ClickHouse; PostgreSQL can also
        # serve this role at moderate scale.
        Analytical = "Analytical"
        # Search / index stores build inverted indexes for fast full-text and faceted
        # search over large data. They are secondary, query-only stores fed from primary
        # data. Examples include OpenSearch and Elasticsearch.
        Search = "Search"
        # Cache stores are thin, transient key-value stores with a time-to-live, used to
        # speed up access to frequently read, rarely changed data. They are NOT a source of
        # truth. Examples include Redis / Valkey and Memcached.
        Cache = "Cache"
        # Spatial databases store geographical or spatial data and are used for location-based queries and analysis.
        # Examples include PostGIS (an extension for PostgreSQL) and Oracle Spatial.
        # Spatial,
        # File or File storage systems are used for storing unstructured data, such as files, images, or blobs.
        # Azure Blob Storage and Amazon S3 are prime examples of file storage systems.
        BlobStore = "BlobStore"

    # The StorageModel property represents the type of data storage or model that the IDataStore is designed to handle.
    # It defines the underlying storage model used by the data store, such as Relational, Document, Vector, etc.
    # This property helps identify what kind of data the store can manage and supports operations specific to the selected model.
    @property
    @abstractmethod
    def StorageModel(self) -> StorageModels:
        ...

    # The ProviderName property represents the name of the underlying database or data provider that the IDataStore is connected to.
    # It identifies the specific database system or service behind the IDataStore implementation.
    # This could be a name like "MongoDB", "Cassandra", "PostgreSQL", etc., depending on which provider is being used.
    # The ProviderName is useful for understanding the context of the data store, such as its behavior, features, and limitations.
    @property
    @abstractmethod
    def ProviderName(self) -> str:
        ...


# Abstract interface for creating stores
class IStoreProvider(ABC):

    @abstractmethod
    def getStore(self, storageModel: IStore.StorageModels) -> IStore:
        ...


# IValidabale is an interface that defines a validation mechanism for entities.
# Classes or structs implementing this interface must provide logic to validate themselves 
# and collect validation errors if any are found.
#
# The validation process ensures that the entity adheres to certain rules or constraints 
# defined in the implementing class.
class IValidable(ABC):

    # Validates the current entity and populates the errors list with any validation errors encountered.
    #
    # @param errors: A list of IValidationError objects that will be populated with errors if the validation fails.
    # @returns: A boolean indicating whether the validation succeeded (true) or failed (false).
    @abstractmethod
    def Validate(self, errors: List[IValidationError]) -> bool:
        ...


# IValidationError is an interface that represents a validation error occurring during the validation process.
# It provides structured details about the nature and location of the error within the entity.
class IValidationError(ABC):

    # Represents the type or class name of the entity where the validation error occurred.
    # For example, it might be "User", "Order", or "Product".
    @property
    @abstractmethod
    def TypeOfEntity(self) -> str:
        ...

    # Indicates the specific member or property of the entity that caused the validation error.
    # For example, it could be "Username", "OrderDate", or "Price".
    @property
    @abstractmethod
    def MemberOfEntity(self) -> str:
        ...

    # Where the error is, relative to the object Validate was called on:
    # "quantity", "items[1].quantity", "billingAddress.country". This is what lets a caller
    # address the failure - mark the right control on a form - instead of only reading a
    # sentence. For a rule on the object's own member it is simply the member name.
    @property
    @abstractmethod
    def Path(self) -> str:
        ...

    # A human-readable description of the error, explaining what went wrong.
    # This is useful for displaying error messages to users or logging them for debugging.
    @property
    @abstractmethod
    def ErrorText(self) -> str:
        ...


# IEntity interface represents a generic entity with an ID and etag.
# The 'etag' is used for versioning or concurrency control in databases, often representing the entity's current version.
# The 'id' is the unique identifier for the entity within the collection or data store.
# These properties ensure that each entity has a unique identifier and version for data integrity.
class IEntity(ABC):

    # The 'id' property represents the unique identifier for the entity.
    # This ID is typically used to reference and retrieve the entity from the data store.
    @property
    @abstractmethod
    def id(self) -> str:
        ...
    @id.setter
    @abstractmethod
    def id(self, value: str) -> None:
        ...

    # The 'etag' property represents the entity's version tag or a unique identifier used for concurrency control.
    # It is typically used to detect changes or updates in the entity, ensuring that the correct version of the entity is being modified.
    @property
    @abstractmethod
    def etag(self) -> str:
        ...
    @etag.setter
    @abstractmethod
    def etag(self, value: str) -> None:
        ...

    # The 'PartitionKey' property represents the key used to partition data in distributed data stores.
    # This allows for more efficient storage and retrieval of entities, especially in large-scale, partitioned systems.
    #
    # Why PartitionKey is Important:
    # - It ensures that related data is grouped together in the same partition, reducing cross-partition queries.
    # - It improves the performance of read and write operations by minimizing data distribution overhead.
    # - It is crucial for ensuring scalability in cloud-based systems like Azure Cosmos DB or Amazon DynamoDB.
    #
    # Example Use Case:
    # In a multi-tenant application, the 'PartitionKey' could be the tenant ID, ensuring that all data
    # for a particular tenant is stored and queried efficiently.
    @property
    @abstractmethod
    def PartitionKey(self) -> str:
        ...
    @PartitionKey.setter
    @abstractmethod
    def PartitionKey(self, value: str) -> None:
        ...

    # The 'LastUpdate' property represents the timestamp of the most recent modification to the entity.
    # This property is crucial for tracking changes and implementing update or audit mechanisms in the system.
    #
    # Why 'LastUpdate' is Important:
    # - It provides a reliable way to determine when an entity was last modified.
    # - Useful for synchronization processes, where only recently modified entities need to be updated.
    # - Enables efficient audit trails by recording the time of changes.
    #
    # Example Use Case:
    # In a content management system, the 'LastUpdate' could be used to display the "Last Modified" date
    # for articles, enabling users to see the freshness of the content.
    #
    # This property is marked as 'readonly' to ensure that the value is managed solely by the system
    # and not directly modified by users, maintaining data integrity.
    @property
    @abstractmethod
    def LastUpdate(self) -> datetime:
        ...
    @LastUpdate.setter
    @abstractmethod
    def LastUpdate(self, value: datetime) -> None:
        ...


class IDocument(IEntity):
    pass


class IDocumentStore(IStore):

    # Asynchronous method to check if a collection exists in the data store.
    # It returns a boolean value, indicating whether the collection with the specified name exists or not.
    # This can be used to verify the presence of a collection before performing operations like retrieval or deletion.
    #
    # @param collectionName - The name of the collection to check for existence.
    # @returns A boolean value indicating if the collection is present in the data store.
    @abstractmethod
    async def IsCollectionExists(self, collectionName: str) -> bool:
        ...

    # Asynchronous method to retrieve a collection by its name from the data store.
    # This method returns the collection as an ICollection of entities.
    # 
    # @param collectionName - The name of the collection to retrieve from the data store.
    # @returns An ICollection representing the collection with the specified name.
    TDocument = TypeVar("TDocument", bound="IDocument")
    @abstractmethod
    async def GetCollectionByName(self, collectionName: str) -> IDocumentCollection[TDocument]:
        ...

    # Asynchronous method to create a new collection in the data store.
    # This method creates a collection with the specified name and returns it as an ICollection of entities of files,
    #
    # @param collectionName - The name of the new collection to be created.
    # @returns The newly created collection, represented as an ICollection
    TDocument = TypeVar("TDocument", bound="IDocument")
    @abstractmethod
    async def CreateCollection(self, collectionName: str) -> IDocumentCollection[TDocument]:
        ...

    # Asynchronous method to drop (delete) an existing collection from the data store.
    # This method removes the specified collection, returning a boolean indicating whether the operation was successful.
    # The collection is represented as an ICollection of entities, files or vectors 
    #
    # @param collectionName - The name of the collection to be dropped from the data store.
    @abstractmethod
    async def DropCollection(self, collectionName: str) -> None:
        ...


TDocument = TypeVar("TDocument", bound="IDocument")
# The ICollection interface defines methods for CRUD operations on entities.
# This interface is used for collections that store entities.
class IDocumentCollection(ABC, Generic[TDocument]):

    # Read-only property for parent Store.
    @property
    @abstractmethod
    def ParentStore(self) -> IStore:
        ...

    # Read-only property representing the name of the collection.
    @property
    @abstractmethod
    def Name(self) -> str:
        ...

    # Asynchronous method to insert an document into the collection.
    # The 'document' parameter is the document that will be inserted into the collection.
    @abstractmethod
    async def Insert(self, document: TDocument) -> None:
        ...

    # Asynchronous method to update an existing document in the collection.
    # The 'document' parameter represents the document to be updated in the collection.
    @abstractmethod
    async def Update(self, document: TDocument) -> None:
        ...

    # Asynchronous method to delete an document using its ID and PartitionKey.
    # The 'id' parameter is the unique identifier of the document, and 'partitionKey' is used for partitioning the data in distributed data stores.
    @abstractmethod
    async def Delete(self, partitionKey: str, id: str) -> None:
        ...

    # Asynchronous method to find an document by its ID and PartitionKey.
    # The 'id' parameter is the unique identifier of the document, and 'partitionKey' is used to partition data.
    # Returns the document if found, or null if not found.
    @abstractmethod
    async def Find(self, partitionKey: str, id: str) -> Optional[TDocument]:
        ...

    # Query interface SCOPED to one partition: the returned queryable is already filtered to
    # documents whose PartitionKey == partitionKey. A caller cannot widen it back (a .Where is
    # additive; a different partitionKey yields an empty result, not a leak), which keeps ad-hoc
    # queries partition-safe by default - mirroring Find(partitionKey, id).
    # Language-mapped: .NET IQueryable<TDocument>, Java Stream<TDocument>, Python Iterable[TDocument].
    @abstractmethod
    def Query(self, partitionKey: str) -> Iterable[TDocument]:
        ...

    # Explicit CROSS-PARTITION query: an unfiltered queryable spanning every partition. Use it
    # deliberately for admin / reporting / migration scans; it is the opt-out from the
    # partition-scoped default and can full-scan (multi-tenant leakage is the caller's concern).
    @abstractmethod
    def QueryCrossPartition(self) -> Iterable[TDocument]:
        ...

    # getting the underlying implementation
    # please use this method carefully, because the returned value is different in every implementation
    @abstractmethod
    def GetUnderlyingImplementation(self) -> Any:
        ...


# The IBlob interface represents a single blob entity in the storage system.
# It extends the IEntity interface to inherit basic entity properties like ID and ETag.
# This interface adds file-specific metadata, such as the file's name and content type.
#
# Examples:
# - A PDF document with the file name "Report.pdf" and MIME type "application/pdf".
# - An image with the file name "photo.png" and MIME type "image/png".
class IBlob(IEntity):

    # The 'fileName' property represents the name of the file as stored in the system.
    # It is primarily used for identification and user-friendly display purposes.
    #
    # Key Characteristics:
    # - Human-readable.
    # - May include file extensions like '.pdf' or '.txt'.
    # - Used in UI to display file names.
    #
    # Example:
    # If a report is stored as 'Monthly_Report.pdf', this property holds the value 'Monthly_Report.pdf'.
    # Applications might use this value to display file names in lists or download dialogs.
    @property
    @abstractmethod
    def fileName(self) -> str:
        ...
    @fileName.setter
    @abstractmethod
    def fileName(self, value: str) -> None:
        ...

    # The 'contentType' property represents the MIME type of the file.
    # It helps systems understand the type of content stored and how to handle or render it.
    #
    # Key Characteristics:
    # - Standardized MIME type format (e.g., 'text/plain', 'application/pdf', 'image/png').
    # - Critical for setting HTTP headers or determining file previews.
    #
    # Examples of MIME Types:
    # - 'text/plain': Plain text files.
    # - 'application/pdf': PDF documents.
    # - 'image/jpeg': JPEG images.
    #
    # Use Cases:
    # - When downloading files, this property can be used to set the correct `Content-Type` header.
    # - In a document viewer, it determines how the file should be displayed (e.g., as a PDF preview).
    @property
    @abstractmethod
    def contentType(self) -> str:
        ...
    @contentType.setter
    @abstractmethod
    def contentType(self, value: str) -> None:
        ...


# The IBlobStore interface defines operations for managing blob storage containers.
# Containers serve as logical units for organizing and isolating blobs.
#
# Examples:
# - A container named 'UserUploads' storing all user-uploaded files.
# - A container named 'Logs' for storing application logs.
class IBlobStore(IStore):

    # Checks whether a container exists in the blob storage.
    #
    # Parameters:
    # - containerName: The name of the container to check.
    #
    # Returns:
    # - Boolean value indicating whether the container exists.
    #
    # Use Case:
    # Before attempting to access or create a container, check if it already exists.
    @abstractmethod
    async def IsContainerExists(self, containerName: str) -> bool:
        ...

    # Retrieves a container by its name.
    #
    # Parameters:
    # - containerName: The name of the container to retrieve.
    #
    # Returns:
    # - An instance of IBlobContainer representing the requested container.
    #
    # Generic Constraint:
    # - TBlob must implement the IBlob interface, ensuring type safety for blob operations.
    #
    # Use Case:
    # Retrieve a container to perform blob operations like uploading or downloading files.
    TBlob = TypeVar("TBlob", bound="IBlob")
    @abstractmethod
    async def GetContainerByName(self, containerName: str) -> IBlobContainer[TBlob]:
        ...

    # Creates a new container in the blob storage.
    #
    # Parameters:
    # - containerName: The name of the container to create.
    #
    # Returns:
    # - An instance of IBlobContainer representing the newly created container.
    #
    # Generic Constraint:
    # - TBlob must implement the IBlob interface, ensuring type safety for blob operations.
    #
    # Use Case:
    # Create a container for a specific group of files, such as user uploads or application logs.
    TBlob = TypeVar("TBlob", bound="IBlob")
    @abstractmethod
    async def CreateContainer(self, containerName: str) -> IBlobContainer[TBlob]:
        ...

    # Deletes an existing container from the blob storage.
    #
    # Parameters:
    # - containerName: The name of the container to delete.
    #
    # Use Case:
    # Remove containers that are no longer needed, freeing up storage space and reducing costs.
    @abstractmethod
    async def DropContainer(self, containerName: str) -> None:
        ...


TBlob = TypeVar("TBlob", bound="IBlob")
# The IBlobContainer interface defines operations for managing blobs within a specific container.
# It provides functionality for uploading, downloading, deleting, and updating blobs, as well as retrieving metadata.
#
# Examples:
# - A container for user-uploaded photos, where each blob represents an image.
# - A container for logs, where each blob is a log file.
class IBlobContainer(ABC, Generic[TBlob]):

    # Read-only property for parent Store.
    @property
    @abstractmethod
    def ParentStore(self) -> IStore:
        ...

    # Read-only property representing the name of the container.
    #
    # Example:
    # If the container is named 'UserFiles', this property holds the value 'UserFiles'.
    @property
    @abstractmethod
    def Name(self) -> str:
        ...

    # Uploads a blob and its content to the container.
    #
    # Parameters:
    # - blob: The blob entity to upload.
    # - content: The stream containing the blob's content.
    #
    # Use Case:
    # Add a new file to the container with its associated metadata.
    @abstractmethod
    async def Upload(self, blob: TBlob, content: BinaryIO) -> None:
        ...

    # Downloads the content of a blob from the container.
    #
    # Parameters:
    # - blob: The blob entity to download.
    #
    # Returns:
    # - A stream containing the blob's content.
    #
    # Use Case:
    # Retrieve a file for viewing or processing.
    @abstractmethod
    async def Download(self, blob: TBlob) -> BinaryIO:
        ...

    # Deletes a blob from the container.
    #
    # Parameters:
    # - partitionKey: The partition key of the blob.
    # - id: The unique identifier of the blob.
    #
    # Use Case:
    # Remove a file that is no longer needed from the container.
    @abstractmethod
    async def Delete(self, partitionKey: str, id: str) -> None:
        ...

    # Finds a blob in the container by its partition key and ID.
    #
    # Parameters:
    # - partitionKey: The partition key of the blob.
    # - id: The unique identifier of the blob.
    #
    # Returns:
    # - A stream containing the blob's content.
    #
    # Use Case:
    # Locate and retrieve a specific file from the container.
    @abstractmethod
    async def Find(self, partitionKey: str, id: str) -> Optional[TBlob]:
        ...

    # Updates the content of an existing blob in the container.
    #
    # Parameters:
    # - blob: The blob entity to update.
    # - content: The stream containing the new content.
    #
    # Use Case:
    # Modify the content of an existing file, such as updating a document.
    @abstractmethod
    async def UpdateContent(self, blob: TBlob, content: BinaryIO) -> None:
        ...

    # Updates the metadata of an existing blob in the container.
    #
    # Parameters:
    # - blob: The blob entity whose metadata is to be updated.
    #
    # Use Case:
    # Modify metadata, such as changing the description or tags associated with a file.
    @abstractmethod
    async def UpdateMetadata(self, blob: TBlob) -> None:
        ...

    # Retrieves the underlying implementation of the blob container.
    #
    # Returns:
    # - A value of type `any` that provides direct access to the underlying storage implementation.
    #
    # Use Case:
    # Use this method for advanced operations that are not covered by the standard interface.
    # Note: This method should be used cautiously, as the returned object is implementation-specific.
    @abstractmethod
    def GetUnderlyingImplementation(self) -> Any:
        ...


class IRow(IEntity):
    pass


# IColumnStore defines a column-oriented logical store interface.
# It extends the general-purpose IStore interface, and adds support for
# table-level operations typically used in column store systems.
# Each table stores typed documents implementing IRow.
# This interface provides a unified way to access column store databases
# like Cassandra, Amazon Redshift, and Google BigQuery.
class IColumnStore(IStore):

    # Asynchronous method to check if a columntable exists in the data store.
    # It returns a boolean value, indicating whether the columntable with the specified name exists or not.
    # This can be used to verify the presence of a columntable before performing operations like retrieval or deletion.
    #
    # @param tableName - The name of the columntable to check for existence.
    # @returns A boolean value indicating if the columntable is present in the data store.
    @abstractmethod
    async def IsTableExists(self, tableName: str) -> bool:
        ...

    # Asynchronous method to retrieve a columntable by its name from the data store.
    # This method returns the columntable as an IColumnTable of entities.
    # 
    # @param tableName - The name of the columntable to retrieve from the data store.
    # @returns An IColumnTable representing the columntable with the specified name.
    TRow = TypeVar("TRow", bound="IRow")
    @abstractmethod
    async def GetTableByName(self, tableName: str) -> IColumnTable[TRow]:
        ...

    # Asynchronous method to create a new columntable in the data store.
    # This method creates a columntable with the specified name and returns it as an IColumnTable of entities of files,
    #
    # @param tableName - The name of the new columntable to be created.
    # @returns The newly created columntable, represented as an IColumnTable
    TRow = TypeVar("TRow", bound="IRow")
    @abstractmethod
    async def CreateTable(self, tableName: str) -> IColumnTable[TRow]:
        ...

    # Asynchronous method to drop (delete) an existing columntable from the data store.
    # This method removes the specified columntable, returning a boolean indicating whether the operation was successful.
    # The columntable is represented as an IColumntable of entities, files or vectors 
    #
    # @param tableName - The name of the columntable to be dropped from the data store.
    @abstractmethod
    async def DropTable(self, tableName: str) -> None:
        ...


TRow = TypeVar("TRow", bound="IRow")
class IColumnTable(ABC, Generic[TRow]):

    # Read-only property for parent Store.
    @property
    @abstractmethod
    def ParentStore(self) -> IStore:
        ...

    # Read-only property representing the name of the table.
    @property
    @abstractmethod
    def Name(self) -> str:
        ...

    # Asynchronous method to insert an row into the columntable.
    # The 'row' parameter is the row that will be inserted into the table.
    @abstractmethod
    async def Insert(self, row: TRow) -> None:
        ...

    # Asynchronous method to update an existing row in the columntable.
    # The 'row' parameter represents the row to be updated in the columntable.
    @abstractmethod
    async def Update(self, row: TRow) -> None:
        ...

    # Asynchronous method to delete an row using its ID and PartitionKey.
    # The 'id' parameter is the unique identifier of the row, and 'partitionKey' is used for partitioning the data in distributed data stores.
    @abstractmethod
    async def Delete(self, partitionKey: str, id: str) -> None:
        ...

    # Asynchronous method to find an row by its ID and PartitionKey.
    # The 'id' parameter is the unique identifier of the row, and 'partitionKey' is used to partition data.
    # Returns the row if found, or null if not found.
    @abstractmethod
    async def Find(self, partitionKey: str, id: str) -> Optional[TRow]:
        ...

    # Query interface SCOPED to one partition: the returned queryable is already filtered to
    # rows whose PartitionKey == partitionKey. A caller cannot widen it back (a .Where is
    # additive; a different partitionKey yields an empty result, not a leak), which keeps ad-hoc
    # queries partition-safe by default - mirroring Find(partitionKey, id). On Cassandra this is
    # a single-partition query (no ALLOW FILTERING).
    # Language-mapped: .NET IQueryable<TRow>, Java Stream<TRow>, Python Iterable[TRow].
    @abstractmethod
    def Query(self, partitionKey: str) -> Iterable[TRow]:
        ...

    # Explicit CROSS-PARTITION query: an unfiltered queryable spanning every partition. Use it
    # deliberately for admin / reporting / migration scans; it is the opt-out from the
    # partition-scoped default and can full-scan (multi-tenant leakage is the caller's concern).
    @abstractmethod
    def QueryCrossPartition(self) -> Iterable[TRow]:
        ...

    # getting the underlying implementation
    # please use this method carefully, because the returned value is different in every implementation
    @abstractmethod
    def GetUnderlyingImplementation(self) -> Any:
        ...


# IRecord represents a single row of a relational (SQL) table.
# It is the relational counterpart of IDocument (document store) and IRow (column store):
# a plain entity (id / etag / PartitionKey / LastUpdate) with no extra members.
class IRecord(IEntity):
    pass


# IRelationalStore is the relational (SQL) logical store. It extends the generic IStore and
# adds table-level operations. A single implementation (backed by linq2db) covers every SQL
# provider (PostgreSQL, Oracle, SQL Server, SQLite): the dialect lives in the provider layer,
# not in this contract or in the caller.
class IRelationalStore(IStore):

    # Asynchronous method to check whether a table exists in the store.
    #
    # @param tableName - The name of the table to check for existence.
    # @returns A boolean value indicating if the table is present in the store.
    @abstractmethod
    async def IsTableExists(self, tableName: str) -> bool:
        ...

    # Asynchronous method to retrieve a table by its name.
    # The row schema is derived from TRecord's mapping.
    #
    # @param tableName - The name of the table to retrieve.
    # @returns An ITable representing the table with the specified name.
    TRecord = TypeVar("TRecord", bound="IRecord")
    @abstractmethod
    async def GetTableByName(self, tableName: str) -> ITable[TRecord]:
        ...

    # Asynchronous method to create a new table.
    # The schema (columns, primary key) is generated from TRecord by the implementation
    # (linq2db CreateTable), so the DDL is dialect-correct without hand-written SQL.
    #
    # @param tableName - The name of the new table to be created.
    # @returns The newly created table, represented as an ITable.
    TRecord = TypeVar("TRecord", bound="IRecord")
    @abstractmethod
    async def CreateTable(self, tableName: str) -> ITable[TRecord]:
        ...

    # Asynchronous method to drop (delete) an existing table from the store.
    #
    # @param tableName - The name of the table to be dropped.
    @abstractmethod
    async def DropTable(self, tableName: str) -> None:
        ...


TRecord = TypeVar("TRecord", bound="IRecord")
# ITable defines CRUD and single-table query operations on a relational table.
# This surface IS portable: it mirrors IDocumentCollection / IColumnTable, so cross-store code
# keeps working. Query() returns the language-native queryable (LINQ in .NET); joins are written
# in the host language over these queryables (advanced multi-table access via GetUnderlyingImplementation).
class ITable(ABC, Generic[TRecord]):

    # Read-only property for parent Store.
    @property
    @abstractmethod
    def ParentStore(self) -> IStore:
        ...

    # Read-only property representing the name of the table.
    @property
    @abstractmethod
    def Name(self) -> str:
        ...

    # Asynchronous method to insert a row into the table.
    # The 'record' parameter is the row that will be inserted into the table.
    @abstractmethod
    async def Insert(self, record: TRecord) -> None:
        ...

    # Asynchronous method to update an existing row in the table.
    # Optimistic concurrency is enforced via the entity's etag.
    @abstractmethod
    async def Update(self, record: TRecord) -> None:
        ...

    # Asynchronous method to delete a row using its PartitionKey and id.
    @abstractmethod
    async def Delete(self, partitionKey: str, id: str) -> None:
        ...

    # Asynchronous method to find a row by its PartitionKey and id.
    # Returns the row if found, or null if not found.
    @abstractmethod
    async def Find(self, partitionKey: str, id: str) -> Optional[TRecord]:
        ...

    # Portable, single-table query SCOPED to one partition: the returned queryable is already
    # filtered to rows whose PartitionKey == partitionKey. A caller cannot widen it back
    # (a .Where is additive; a different partitionKey yields an empty result, not a leak), which
    # keeps ad-hoc queries partition-safe by default - mirroring Find(partitionKey, id).
    # Language-mapped: .NET IQueryable<TRecord>, Java Stream<TRecord>, ...
    @abstractmethod
    def Query(self, partitionKey: str) -> Iterable[TRecord]:
        ...

    # Explicit CROSS-PARTITION query: an unfiltered queryable spanning every partition. Use it
    # deliberately for admin / reporting / migration scans; it is the opt-out from the
    # partition-scoped default and can full-scan (multi-tenant leakage is the caller's concern).
    @abstractmethod
    def QueryCrossPartition(self) -> Iterable[TRecord]:
        ...

    # Getting the underlying implementation.
    # Please use this method carefully, because the returned value is different in every
    # implementation (e.g. the linq2db DataConnection, or the raw DbConnection for Dapper).
    @abstractmethod
    def GetUnderlyingImplementation(self) -> Any:
        ...


# IEvent represents a single immutable event appended to a stream.
# It is deliberately NOT an IEntity: events are versioned by their STREAM (not by a per-event
# etag) and are never updated or deleted individually. An event is an append-only fact.
class IEvent(ABC):

    # The unique identifier of this event, primarily used for idempotency and de-duplication.
    # If left empty on append, the store assigns one.
    @property
    @abstractmethod
    def eventId(self) -> str:
        ...
    @eventId.setter
    @abstractmethod
    def eventId(self, value: str) -> None:
        ...

    # The stream this event belongs to (typically an aggregate instance id, or an audit
    # category id). Set by the store on append.
    @property
    @abstractmethod
    def streamId(self) -> str:
        ...
    @streamId.setter
    @abstractmethod
    def streamId(self, value: str) -> None:
        ...

    # The zero-based position of the event within its stream. This is the stream's
    # optimistic-concurrency token. Set by the store on append.
    @property
    @abstractmethod
    def version(self) -> int:
        ...
    @version.setter
    @abstractmethod
    def version(self, value: int) -> None:
        ...

    # The logical event type name, used for routing and for deserializing 'data' back into a
    # concrete event type (e.g. "OrderPlaced", "PasswordChanged").
    @property
    @abstractmethod
    def eventType(self) -> str:
        ...
    @eventType.setter
    @abstractmethod
    def eventType(self, value: str) -> None:
        ...

    # The serialized event payload (JSON).
    @property
    @abstractmethod
    def data(self) -> str:
        ...
    @data.setter
    @abstractmethod
    def data(self, value: str) -> None:
        ...

    # Optional serialized metadata that travels with the event but is not part of its payload,
    # such as correlation id, causation id or the acting user (JSON).
    @property
    @abstractmethod
    def metadata(self) -> str:
        ...
    @metadata.setter
    @abstractmethod
    def metadata(self, value: str) -> None:
        ...

    # The moment the event was recorded. Set by the store on append.
    @property
    @abstractmethod
    def timestamp(self) -> datetime:
        ...
    @timestamp.setter
    @abstractmethod
    def timestamp(self, value: datetime) -> None:
        ...


# IEventStore is an append-only, immutable, ordered stream store. It is a storage MODEL;
# event sourcing and audit trails are USES of it - both domain events and audit events are
# just events on streams. A single implementation family can be backed by EventStoreDB, by
# Cassandra (partition = stream, clustering = version), or by an in-memory store for testing.
class IEventStore(IStore):

    # Appends events to the end of a stream with optimistic concurrency.
    #
    # @param streamId - the target stream (aggregate/category id).
    # @param expectedVersion - the caller's last-known version of the stream. Sentinels:
    #        -2 = Any (no concurrency check); -1 = the stream must not yet exist (empty);
    #        >= 0 = the stream's current last version must equal this value, otherwise the
    #        append is rejected as a concurrency conflict.
    # @param events - the events to append, in order.
    # @returns the new last version of the stream after the append.
    @abstractmethod
    async def AppendToStream(self, streamId: str, expectedVersion: int, events: List[IEvent]) -> int:
        ...

    # Reads a slice of a stream forward, in ascending version order.
    #
    # @param streamId - the stream to read.
    # @param fromVersion - the zero-based version to start reading from.
    # @param maxCount - the maximum number of events to return; -1 means "read to the end".
    # @returns the events in ascending version order; empty if the stream does not exist.
    @abstractmethod
    async def ReadStream(self, streamId: str, fromVersion: int, maxCount: int) -> List[IEvent]:
        ...

    # Checks whether a stream exists (has at least one event).
    #
    # @param streamId - the stream to check.
    # @returns true if the stream exists.
    @abstractmethod
    async def StreamExists(self, streamId: str) -> bool:
        ...

    # Returns the current last version of a stream, or -1 if the stream does not exist.
    #
    # @param streamId - the stream to inspect.
    @abstractmethod
    async def GetStreamVersion(self, streamId: str) -> int:
        ...

    # Deletes (tombstones) an entire stream. Individual events are never deleted; this removes
    # the whole stream (e.g. for GDPR erasure). expectedVersion follows the AppendToStream
    # sentinels.
    #
    # @param streamId - the stream to delete.
    # @param expectedVersion - concurrency guard, see AppendToStream.
    @abstractmethod
    async def DeleteStream(self, streamId: str, expectedVersion: int) -> None:
        ...

    # Getting the underlying implementation.
    # Please use this method carefully, because the returned value is different in every
    # implementation. This is also where PROVIDER-SPECIFIC, non-portable capabilities live -
    # most notably subscriptions / projections / category ($all) reads, which are native in
    # EventStoreDB but emulated or limited on other backends.
    @abstractmethod
    def GetUnderlyingImplementation(self) -> Any:
        ...


# IAnalyticalRecord is the marker for a denormalized "fact" row in an analytical (OLAP) store.
# It is deliberately NOT an IEntity: analytical rows have no per-row identity, etag or
# concurrency control - they are append-only facts whose columns (dimensions and measures) are
# defined entirely by the concrete record's mapping. It carries ONE routing column, PartitionKey,
# so a fact table can be queried tenant-scoped (Query(partitionKey)) as well as across every
# partition (QueryCrossPartition), matching the operational stores - but there is still no id or
# etag (a fact has a partition, not an identity).
class IAnalyticalRecord(ABC):

    # The partition (e.g. tenant) this fact belongs to. It is the ONLY identity-like column on a
    # fact row: there is no id or etag. It scopes Query(partitionKey) and, for backends that
    # support it, is the natural clustering/partitioning column of the fact table.
    @property
    @abstractmethod
    def PartitionKey(self) -> str:
        ...
    @PartitionKey.setter
    @abstractmethod
    def PartitionKey(self, value: str) -> None:
        ...


# IAnalyticalStore is a columnar OLAP / analytical store: batch (bulk) append on the write side,
# aggregation-oriented queries on the read side. It is a storage MODEL; reporting and BI are USES
# of it. Data typically lands here in PROCESSED form, projected from events or audit events by the
# consuming application - that projection pipeline is NOT part of PolyPersist; this store only
# provides the surface. Backends must speak SQL so the read side can use the same query engine as
# the relational store: ClickHouse (native OLAP), PostgreSQL (at moderate scale), or an in-memory
# store for testing. Cassandra is NOT a valid backend here (no SQL, not built for ad-hoc aggregation).
class IAnalyticalStore(IStore):

    # Checks whether a fact table exists in the store.
    @abstractmethod
    async def IsTableExists(self, tableName: str) -> bool:
        ...

    # Retrieves a fact table by name. The row schema is derived from TRecord's mapping.
    TRecord = TypeVar("TRecord", bound="IAnalyticalRecord")
    @abstractmethod
    async def GetTableByName(self, tableName: str) -> IAnalyticalTable[TRecord]:
        ...

    # Creates a new fact table. The schema is generated from TRecord by the implementation.
    TRecord = TypeVar("TRecord", bound="IAnalyticalRecord")
    @abstractmethod
    async def CreateTable(self, tableName: str) -> IAnalyticalTable[TRecord]:
        ...

    # Drops an existing fact table.
    @abstractmethod
    async def DropTable(self, tableName: str) -> None:
        ...


TRecord = TypeVar("TRecord", bound="IAnalyticalRecord")
# IAnalyticalTable represents a single fact table. Writing is BATCH-first (bulk append); there is
# deliberately NO per-row Insert / Update / Delete / Find, because that would misrepresent an OLAP
# engine (single-row writes are an anti-pattern; row mutation is a heavy async operation).
class IAnalyticalTable(ABC, Generic[TRecord]):

    # Read-only property for parent Store.
    @property
    @abstractmethod
    def ParentStore(self) -> IStore:
        ...

    # Read-only property representing the name of the table.
    @property
    @abstractmethod
    def Name(self) -> str:
        ...

    # Bulk-appends a batch of fact rows. This is the only write path: OLAP engines are optimized
    # for batched ingestion, so callers should accumulate rows and append them together.
    @abstractmethod
    async def InsertBatch(self, records: List[TRecord]) -> None:
        ...

    # Single-table analytical query (aggregation / GROUP BY / scan) SCOPED to one partition: the
    # returned queryable is already filtered to rows whose PartitionKey == partitionKey. Use it
    # for tenant-scoped analytics; a caller cannot widen it back across partitions.
    # Language-mapped: .NET IQueryable<TRecord>, Java Stream<TRecord>, ...
    @abstractmethod
    def Query(self, partitionKey: str) -> Iterable[TRecord]:
        ...

    # Explicit CROSS-PARTITION analytical query: an unfiltered queryable spanning every partition.
    # This is the natural BI / reporting path for an OLAP store (aggregate across all tenants);
    # it is the deliberate opt-out from the partition-scoped Query.
    @abstractmethod
    def QueryCrossPartition(self) -> Iterable[TRecord]:
        ...

    # Getting the underlying implementation.
    # Please use this method carefully, because the returned value is different in every
    # implementation (e.g. the linq2db DataConnection, or the raw DbConnection).
    @abstractmethod
    def GetUnderlyingImplementation(self) -> Any:
        ...


# ISearchDocument is the marker for a document held in a search index.
# It is deliberately NOT an IEntity: a search document is a denormalized, derived projection of
# primary data, so it carries no etag / partition / concurrency - only an 'id' used to address
# the document for indexing (upsert) and deletion.
class ISearchDocument(ABC):

    # The identifier of the document within the index, used to upsert and delete it.
    @property
    @abstractmethod
    def id(self) -> str:
        ...
    @id.setter
    @abstractmethod
    def id(self, value: str) -> None:
        ...


# ISearchStore is a full-text search / index store (e.g. OpenSearch). It is a storage MODEL;
# searching is a USE. It is a SECONDARY, query-only store: documents are indexed here as a
# derived projection of primary data (that projection pipeline is app/consumer logic, NOT part
# of PolyPersist; this store only provides the surface).
#
# The read side is NOT SQL/linq2db - search is expressed in the engine's own query model.
# Therefore only a thin, portable core is exposed here (index / delete / simple full-text search);
# advanced capabilities (relevance tuning, facets/aggregations, highlighting, suggestions) are
# reached through GetUnderlyingImplementation with the native client.
#
# Backends: OpenSearch (native), an in-memory store for testing, and PostgreSQL full-text search
# for moderate needs.
class ISearchStore(IStore):

    # Checks whether an index exists in the store.
    @abstractmethod
    async def IsIndexExists(self, indexName: str) -> bool:
        ...

    # Retrieves an index by name. The document schema is derived from TDocument's mapping.
    TDocument = TypeVar("TDocument", bound="ISearchDocument")
    @abstractmethod
    async def GetIndexByName(self, indexName: str) -> ISearchIndex[TDocument]:
        ...

    # Creates a new index. The mapping is derived from TDocument by the implementation.
    TDocument = TypeVar("TDocument", bound="ISearchDocument")
    @abstractmethod
    async def CreateIndex(self, indexName: str) -> ISearchIndex[TDocument]:
        ...

    # Drops an existing index.
    @abstractmethod
    async def DropIndex(self, indexName: str) -> None:
        ...


TDocument = TypeVar("TDocument", bound="ISearchDocument")
# ISearchIndex represents a single search index. Documents are indexed (upserted) by id and
# deleted by id. The Search method covers the common full-text case; anything more advanced goes
# through GetUnderlyingImplementation.
class ISearchIndex(ABC, Generic[TDocument]):

    # Read-only property for parent Store.
    @property
    @abstractmethod
    def ParentStore(self) -> IStore:
        ...

    # Read-only property representing the name of the index.
    @property
    @abstractmethod
    def Name(self) -> str:
        ...

    # Indexes (upserts) a single document by its id.
    @abstractmethod
    async def Index(self, document: TDocument) -> None:
        ...

    # Indexes (upserts) a batch of documents in one round-trip.
    @abstractmethod
    async def IndexBatch(self, documents: List[TDocument]) -> None:
        ...

    # Removes a document from the index by its id.
    @abstractmethod
    async def Delete(self, id: str) -> None:
        ...

    # Full-text search over the index, with paging.
    #
    # @param queryText - the free-text query.
    # @param mode - FullText (exact, whole-word, fast) or Fuzzy (substring + typo tolerant, slower).
    # @param from - the zero-based offset of the first hit to return.
    # @param size - the maximum number of hits to return.
    # @returns the matching documents, most relevant first.
    @abstractmethod
    async def Search(self, queryText: str, mode: SearchMode, from_: int, size: int) -> List[TDocument]:
        ...

    # Getting the underlying implementation.
    # Please use this method carefully, because the returned value is different in every
    # implementation. This is where PROVIDER-SPECIFIC search capabilities live (relevance
    # tuning, facets / aggregations, highlighting, suggesters), which are not portable.
    @abstractmethod
    def GetUnderlyingImplementation(self) -> Any:
        ...


T = TypeVar("T")
# ICacheEntry is the outcome of a TryGet lookup: whether the key was there, and what it held.
#
# Get returns the type default when a key is absent, which is unambiguous only for reference
# types. For a VALUE type it is not: a cached 0, false or DateTime.MinValue is indistinguishable
# from a miss, so the caller either recomputes a perfectly good cached value or has to call
# Exists first - two round trips, with a race in between. This carrier answers both questions in
# one call. It is deliberately a return value rather than an out-parameter, because out-parameters
# do not exist in every target language.
class ICacheEntry(ABC, Generic[T]):

    # True if the key was present and had not expired; false for a miss.
    @property
    @abstractmethod
    def Found(self) -> bool:
        ...

    # The cached value when Found is true; the type default otherwise.
    @property
    @abstractmethod
    def Value(self) -> T:
        ...


# ICacheStore is a thin key-value cache with time-to-live. It is NOT a source of truth: values
# are transient and may be evicted or expire at any time. It is a storage MODEL (key-value + TTL);
# the caching STRATEGY (cache-aside, write-through, invalidation, repository decoration) is a
# cross-cutting service concern that belongs to SrvKit, which builds on top of this surface.
#
# Values are arbitrary (a DTO, a string, a list, ...): the generic type is intentionally
# unconstrained, and the implementation serializes/deserializes it. Backends are key-value
# caches: Redis / Valkey (distributed, default), Memcached, an in-process memory cache (L1 /
# testing) or a managed equivalent.
class ICacheStore(IStore):

    # Stores a value under a key with a time-to-live.
    #
    # @param key - the cache key.
    # @param value - the value to cache; serialized by the implementation.
    # @param ttlSeconds - the time-to-live in seconds; a value <= 0 means no expiration.
    T = TypeVar("T")
    @abstractmethod
    async def Set(self, key: str, value: T, ttlSeconds: int) -> None:
        ...

    # Reads a value by key.
    #
    # @param key - the cache key.
    # @returns the cached value, or the type default (null for reference types) if the key is
    #          absent or has expired.
    T = TypeVar("T")
    @abstractmethod
    async def Get(self, key: str) -> T:
        ...

    # Reads a value by key, reporting whether it was there at all.
    #
    # Prefer this over Get whenever T can be a value type, or whenever "absent" and "cached
    # default" have to be told apart. It answers in a single round trip what Exists + Get would
    # answer in two (and without the race between them).
    #
    # @param key - the cache key.
    # @returns an entry whose Found is true and Value is the cached value, or whose Found is
    #          false when the key is absent or has expired.
    T = TypeVar("T")
    @abstractmethod
    async def TryGet(self, key: str) -> ICacheEntry[T]:
        ...

    # Checks whether a (non-expired) value exists for a key.
    @abstractmethod
    async def Exists(self, key: str) -> bool:
        ...

    # Removes a value from the cache by key (a no-op if it is not present).
    @abstractmethod
    async def Remove(self, key: str) -> None:
        ...

    # Getting the underlying implementation.
    # Please use this method carefully, because the returned value is different in every
    # implementation. This is where PROVIDER-SPECIFIC capabilities live that the thin cache
    # surface does not expose (e.g. atomic counters, pub/sub, native data structures in Redis).
    @abstractmethod
    def GetUnderlyingImplementation(self) -> Any:
        ...


class ITransaction(ABC):


    # Defines supported transactional operations.
    class Operations(Enum):
        Insert = "Insert"
        Update = "Update"
        Delete = "Delete"

    # Adds an existing document to the transaction for change tracking.
    TDocument = TypeVar("TDocument", bound="IDocument")
    @abstractmethod
    def AddOriginal(self, collection: IDocumentCollection[TDocument], document: TDocument) -> None:
        ...

    # Adds an existing row to the transaction for change tracking.
    TRow = TypeVar("TRow", bound="IRow")
    @abstractmethod
    def AddOriginal(self, table: IColumnTable[TRow], row: TRow) -> None:
        ...

    # Adds an existing relational row to the transaction for change tracking.
    TRecord = TypeVar("TRecord", bound="IRecord")
    @abstractmethod
    def AddOriginal(self, table: ITable[TRecord], record: TRecord) -> None:
        ...

    # Adds an existing blob to the transaction for change tracking, including its content snapshot.
    TBlob = TypeVar("TBlob", bound="IBlob")
    @abstractmethod
    async def AddOriginal(self, container: IBlobContainer[TBlob], blob: TBlob) -> None:
        ...

    # Inserts a new document and registers a rollback action to delete it if needed.
    TDocument = TypeVar("TDocument", bound="IDocument")
    @abstractmethod
    async def Insert(self, collection: IDocumentCollection[TDocument], document: TDocument) -> None:
        ...

    # Inserts a new row and registers a rollback action to delete it if needed.
    TRow = TypeVar("TRow", bound="IRow")
    @abstractmethod
    async def Insert(self, table: IColumnTable[TRow], row: TRow) -> None:
        ...

    # Inserts a new relational row and registers a rollback action to delete it if needed.
    TRecord = TypeVar("TRecord", bound="IRecord")
    @abstractmethod
    async def Insert(self, table: ITable[TRecord], record: TRecord) -> None:
        ...

    # Uploads a new blob and registers a rollback action to delete it if needed.
    TBlob = TypeVar("TBlob", bound="IBlob")
    @abstractmethod
    async def Upload(self, container: IBlobContainer[TBlob], blob: TBlob, content: BinaryIO) -> None:
        ...

    # Updates an existing document and registers a rollback action to restore its original state if needed.
    TDocument = TypeVar("TDocument", bound="IDocument")
    @abstractmethod
    async def Update(self, collection: IDocumentCollection[TDocument], document: TDocument) -> None:
        ...

    # Updates an existing row and registers a rollback action to restore its original state if needed.
    TRow = TypeVar("TRow", bound="IRow")
    @abstractmethod
    async def Update(self, table: IColumnTable[TRow], row: TRow) -> None:
        ...

    # Updates an existing relational row and registers a rollback action to restore its original state if needed.
    TRecord = TypeVar("TRecord", bound="IRecord")
    @abstractmethod
    async def Update(self, table: ITable[TRecord], record: TRecord) -> None:
        ...

    # Updates the content of an existing blob and registers a rollback action to restore its original content if needed.
    TBlob = TypeVar("TBlob", bound="IBlob")
    @abstractmethod
    async def UpdateContent(self, container: IBlobContainer[TBlob], blob: TBlob, content: BinaryIO) -> None:
        ...

    # Updates the metadata of an existing blob and registers a rollback action to restore its original metadata if needed.
    TBlob = TypeVar("TBlob", bound="IBlob")
    @abstractmethod
    async def UpdateMetadata(self, container: IBlobContainer[TBlob], blob: TBlob) -> None:
        ...

    # Deletes an existing document and registers a rollback action to re-insert its original state if needed.
    TDocument = TypeVar("TDocument", bound="IDocument")
    @abstractmethod
    async def Delete(self, collection: IDocumentCollection[TDocument], document: TDocument) -> None:
        ...

    # Deletes an existing row and registers a rollback action to re-insert its original state if needed.
    TRow = TypeVar("TRow", bound="IRow")
    @abstractmethod
    async def Delete(self, table: IColumnTable[TRow], row: TRow) -> None:
        ...

    # Deletes an existing relational row and registers a rollback action to re-insert its original state if needed.
    TRecord = TypeVar("TRecord", bound="IRecord")
    @abstractmethod
    async def Delete(self, table: ITable[TRecord], record: TRecord) -> None:
        ...

    # Deletes an existing blob and registers a rollback action to re-upload its original state if needed.
    TBlob = TypeVar("TBlob", bound="IBlob")
    @abstractmethod
    async def Delete(self, container: IBlobContainer[TBlob], blob: TBlob) -> None:
        ...

    # Writes everything the transaction has collected, in the order it was collected.
    #
    # Nothing reached a store before this call: every operation was queued, so a Rollback before
    # the commit costs nothing and no reader ever saw a half-finished change. Inside the commit a
    # store that can offer a native database transaction gets one and commits LAST, after every
    # compensation-only store has succeeded - so a failure costs that store a free ROLLBACK, and
    # only the stores that cannot do better are compensated. With more than one native
    # participant the guarantee degrades to "all but one commit atomically"; there is no
    # two-phase commit. Registered commit actions run afterwards, once the data is durable.
    @abstractmethod
    async def Commit(self) -> None:
        ...

    # Abandons the transaction. Before a commit this simply drops the queued operations; after a
    # partial commit it runs the compensations in reverse order.
    @abstractmethod
    async def Rollback(self) -> None:
        ...
